### ISSUE TITLE
Enable UnittedQuantity handling in the SWI-Prolog-based reasoner/translator pair

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#1043]
Hooks are there, just need to do implementation.

**Comment by crapo** [comment]
@tuxji , on branch GH-1043 I did as you requested in your comments on the last PR on GH-1041. When all tests passed and I was ready to create a PR I did a "git fetch && git rebase origin/development".  As a result I got the following, which appeared reasonable:

remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 17 (delta 5), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (17/17), 9.44 KiB | 3.15 MiB/s, done.
From https://github.com/crapo/sadlos2
 + 5f24b0ab4...ce7f0ea03 dependabot/maven/sadl3/com.ge.research.sadl.parent/version.tycho-3.0.3 -> origin/dependabot/maven/sadl3/com.ge.research.sadl.parent/version.tycho-3.0.3  (forced update)
   065a48231..3c3ee5db4  development                                                            -> origin/development
dropping 4ba496dd669ee806244c6f2e36679db32839942d removed incorrect Import-Package that was preventing JeanAugmentedReasonerPlugin from being loaded by ServiceLoader -- patch contents already upstream
Successfully rebased and updated refs/heads/GH-1043.

**"git status" then produced**

Your branch and 'origin/GH-1043' have diverged,
and have 5 and 5 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

**So, I did a "git pull", which produced**

hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.

I am not sure how to accomplish updating GH-1043 with any changes made to development so that I can do a final run of all tests before creating a PR. As you noted, in the past I have committed changes to my branch, ran all tests, pulled development and merged with my branch, ran all tests again, pushed, and then, when github told me there were no conflicts, created a PR. As I had asked on the old PR, I don't understand the difference and clearly I don't understand how to comply with your request.

**Comment by tuxji** [comment]
@crapo , you don't need to run a "git pull" at all.  Your branch is already set up the way it's supposed to be: a set of commits rebased against the latest commits in origin/development.  Your "git status" gave you wrong advice; you were supposed to run "git push --force-with-lease" to replace the commits in origin/GH-1043 with your newly rebased commits and then do a final run of all tests before creating a PR.  If the "git pull" messed up your branch, try to reset it back to the commit it had before the "git pull".  You can also run "git diff origin/development..HEAD" to check that the changes look like what you expect them to look like before you push them.

**Comment by crapo** [comment]
Finished implementation of support for UnittedQuantity in SWI-Prolog reasoner/translator. Includes fixes to issues encountered, the main one being a scoping issue that did not allow SadlBuiltinFunctions.sadl to reference types defined in SadlImplicitModel.sadl. Also includes tests for new functionality.
