### ISSUE TITLE
Update Web SADL

### ISSUE THREAD

**Issue by kittaakos** [SemanticApplicationDesignLanguage/sadl#398]
The development is on the [`web-sadl-semtk`](https://github.com/crapo/sadlos2/tree/web-sadl-semtk) branch.
The WIP PR is [here](https://github.com/crapo/sadlos2/pull/397).

TODOs:
  -  [ ] Move to Azure:
    - can build both Windows and Linux,
    - can share states between build stages without external storage. Travis CI [can't](https://docs.travis-ci.com/user/build-stages#data-persistence-between-stages-and-jobs). Currently, we run the Maven build twice, which causes an additional 5-10 minutes penalty.

**Comment by crapo** [comment]
You mentioned that the Eclipse version needed to be the latest. What version exactly?

**Comment by kittaakos** [comment]
> What version exactly?

I do not know yet. Most likely, the target platform update does not affect the Eclipse SDK version. I am still working on the build.

**Comment by crapo** [comment]
As soon as you are ready, we'd like you to demo WebSADL to the SemTK folks here, answer questions about architecture and git integration, and discuss with us the general goals and approach to integration. Please let me know when that can happen.

**Comment by kittaakos** [comment]
> TODOs:
> 
> * [ ]  Move to Azure:
>   - can build both Windows and Linux,
>   - can share states between build stages without external storage. Travis CI [can't](https://docs.travis-ci.com/user/build-stages#data-persistence-between-stages-and-jobs). Currently, we run the Maven build twice, which causes an additional 5-10 minutes penalty.

_WONTFIX_. I had to keep AppVeyor for the Windows build. The details are [here](https://github.com/crapo/sadlos2/pull/397#issuecomment-586870271).

> As soon as you are ready, we'd like you to demo WebSADL to the SemTK folks here, answer questions about architecture

Sure, please schedule a call for the demo via email.

> and git integration

It is very much limited. A working solution is documented [here](https://github.com/eclipse-theia/theia/issues/1037#issuecomment-376180725), but Theia does not support workspace-hosting, authentication, and authorization. We can discuss the details during our call.

I am going to close this issue. Please add any comments, remarks to [the PR](https://github.com/crapo/sadlos2/pull/397) instead.
