### ISSUE TITLE
Demo and Integration Planning

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#400]
@kittaakos , I thought I posted or emailed this last week but can't seem to find it. As soon as you are ready with updated WebSADL, we'd like to schedule a demo where you show WebSADL capability to the SemTK folks, including and of special interest the git integration possibilities. Then we can discuss the integration goals and how best to architect the integrated system. Please let me know when you think we might have such a meeting.

**Comment by kittaakos** [comment]
> I thought I posted

Yes, you did. https://github.com/crapo/sadlos2/issues/398#issuecomment-586887490

Please schedule a call via email. Thank you!
