### ISSUE TITLE
Failing test in SadlImportManagerProviderTest

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#402]
@kittaakos , not sure what might have changed, but this test now fails with this exception:

4    [main] ERROR org.eclipse.xtext.validation.CompositeEValidator  - Error executing EValidator
java.lang.IllegalArgumentException: Expected a `platform:/resource/` URI. Got instead: __synthetic0.sadl.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:93)
	at com.ge.research.sadl.utils.EclipseSadlProjectHelper.checkUri(EclipseSadlProjectHelper.java:149)

Fuzzy on what might have changed--I'm not aware of any changes that would affect this.

Branch is MissingPatterns. Test is currently Ignored.

**Comment by kittaakos** [comment]
What's the rest of the stacktrace?

**Comment by crapo** [comment]
Humm... this test now passes, both in Eclipse and during Maven install. Not sure what was going on. I don't think I'm crazy :-)
