### ISSUE TITLE
Further CA improvements

### ISSUE THREAD

**Issue by kittaakos** [SemanticApplicationDesignLanguage/sadl#412]
@crapo wrote [here](https://github.com/crapo/sadlos2/issues/406#issuecomment-600576005):
> Create a new model.
> Add line "area is a property with values of type float."
> Add a line "Shape is a class described by "
> With cursor at the end of this line, ask for content assist; none is available.
> Arguably "area" should be on the list as adding "area" to this statement would be a reasonable thing to do and would put "Shape" in its domain.
> The filter would be properties that do not have "Shape" or any of its super classes in its domain.
> If this is just an ontology query issue, I can handle it if you would please point me to where the fix would go.

**Comment by crapo** [comment]
@kittaakos , given that I can't merge MissingPatterns with development now, for the reasons we discussed, how difficult would it be for you to create a PR for MissingPatterns that would pull all of the improvements to CA that you have done into MissingPatterns?

**Comment by kittaakos** [comment]
> MissingPatterns that would pull all of the improvements to CA

Here is the PR: https://github.com/crapo/sadlos2/pull/413

**Comment by kittaakos** [comment]
The changes are part of https://github.com/crapo/sadlos2/pull/416.
