### ISSUE TITLE
Missing a plugin

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#414]
@kittaakos , when I try to run a JUnit Plugin Test in Eclipse, I get this error (including all of console output):

!SESSION 2020-03-31 17:36:39.952 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_241
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -version 3 -port 52617 -testLoaderClass org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader -loaderpluginname org.eclipse.jdt.junit4.runtime -test com.ge.research.sadl.ui.tests.SadlModelArticleUITest:testCRule_02 -application org.eclipse.pde.junit.runtime.uitestapplication -product org.eclipse.platform.ide -testpluginname com.ge.research.sadl.ui.tests
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -consoleLog -version 3 -port 52617 -testLoaderClass org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader -loaderpluginname org.eclipse.jdt.junit4.runtime -test com.ge.research.sadl.ui.tests.SadlModelArticleUITest:testCRule_02 -application org.eclipse.pde.junit.runtime.uitestapplication -product org.eclipse.platform.ide -data C:\sadl\ws/../junit-workspace -dev file:C:/sadl/ws/.metadata/.plugins/org.eclipse.pde.core/pde-junit/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -testpluginname com.ge.research.sadl.ui.tests

!ENTRY org.eclipse.pde.junit.runtime 4 0 2020-03-31 17:36:42.093
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.pde.junit.runtime [270]
  Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit.runtime; bundle-version="[3.5.0,4.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:451)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1783)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1762)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1725)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1656)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:233)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:343)

!ENTRY org.eclipse.pde.junit.runtime 2 0 2020-03-31 17:36:44.159
!MESSAGE Could not resolve module: org.eclipse.pde.junit.runtime [270]
  Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit.runtime; bundle-version="[3.5.0,4.0.0)"

!ENTRY org.eclipse.osgi 4 0 2020-03-31 17:36:44.160
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "org.eclipse.pde.junit.runtime.uitestapplication" could not be found in the registry. The applications available are: com.ge.research.sadl.applications.ExecuteCommand, org.eclipse.ant.core.antRunner, org.eclipse.ant.ui.antRunner, org.eclipse.e4.ui.workbench.swt.E4Application, org.eclipse.e4.ui.workbench.swt.GenTopic, org.eclipse.emf.codegen.CodeGen, org.eclipse.emf.codegen.JMerger, org.eclipse.emf.codegen.ecore.Generator, org.eclipse.emf.importer.ecore.Ecore2GenModel, org.eclipse.emf.importer.java.Java2GenModel, org.eclipse.emf.importer.rose.Rose2GenModel, org.eclipse.emf.mwe.core.WorkflowRunner, org.eclipse.equinox.app.error, org.eclipse.equinox.p2.director, org.eclipse.equinox.p2.garbagecollector.application, org.eclipse.equinox.p2.publisher.InstallPublisher, org.eclipse.equinox.p2.publisher.EclipseGenerator, org.eclipse.equinox.p2.publisher.ProductPublisher, org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher, org.eclipse.equinox.p2.reconciler.application, org.eclipse.equinox.p2.repository.repo2runnable, org.eclipse.equinox.p2.repository.metadataverifier, org.eclipse.equinox.p2.artifact.repository.mirrorApplication, org.eclipse.equinox.p2.metadata.repository.mirrorApplication, org.eclipse.equinox.p2.touchpoint.natives.nativePackageExtractor, org.eclipse.equinox.p2.updatesite.UpdateSitePublisher, org.eclipse.equinox.p2.publisher.UpdateSitePublisher, org.eclipse.equinox.p2.publisher.CategoryPublisher, org.eclipse.help.base.infocenterApplication, org.eclipse.help.base.helpApplication, org.eclipse.help.base.indexTool, org.eclipse.jdt.apt.core.aptBuild, org.eclipse.jdt.core.JavaCodeFormatter, org.eclipse.jdt.core.JavaIndexer, org.eclipse.pde.build.Build, org.eclipse.ui.ide.workbench.
	at org.eclipse.equinox.internal.app.EclipseAppContainer.startDefaultApp(EclipseAppContainer.java:252)
	at org.eclipse.equinox.internal.app.MainApplicationLauncher.run(MainApplicationLauncher.java:33)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1474)
An error has occurred. See the log file
C:\sadl\junit-workspace\.metadata\.log.

**Comment by kittaakos** [comment]
You have an incorrect launch config configured somewhere. The `com.ge.research.sadl.ui.tests.SadlModelArticleUITest.testCRule_02()` runs without any problem. 
 - You can check what's wrong with your  launch config:
![screencast 2020-04-01 10-15-20](https://user-images.githubusercontent.com/1405703/78114845-2d7aca80-7402-11ea-9ea2-0ad09303d559.gif)

 - You can also delete the launch config for the test and re-run the test:
![screencast 2020-04-01 10-19-11](https://user-images.githubusercontent.com/1405703/78115005-73d02980-7402-11ea-9dee-e937b1aa19d8.gif)

[Here](https://www.vogella.com/tutorials/EclipsePlugin/article.html#checklist-for-common-launch-problems) is a blog about `Checklist for common launch problems`.

If you cannot solve the problem with the suggested ways, I am available for a tcon, but as I see nothing is wrong with the code and the test.

**Comment by crapo** [comment]
@kittaakos , I had just created that debug configuration, and deleting it and running again does not change anything. Verify plugins says everything is fine. The error message says:

Unresolved requirement: Require-Bundle: org.eclipse.jdt.junit.runtime; bundle-version="[3.5.0,4.0.0)"

This is specified on the command line for the test, according to the console output:

Command-line arguments:  -os win32 -ws win32 -arch x86_64 -consoleLog -version 3 -port 62294 -testLoaderClass org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader -loaderpluginname org.eclipse.jdt.junit4.runtime -test com.ge.research.sadl.ui.tests.SadlModelArticleUITest:testCRule_02 **-application org.eclipse.pde.junit.runtime.uitestapplication** -product org.eclipse.platform.ide -data C:\sadl\ws/../junit-workspace -dev file:C:/sadl/ws/.metadata/.plugins/org.eclipse.pde.core/pde-junit/dev.properties -os win32 -ws win32 -arch x86_64 -consoleLog -testpluginname com.ge.research.sadl.ui.tests

I've searched all files and don't see this in any file in the workspace, so I assume that this isn't an issue with a MANIFEST file. I don't find anything in the launch problems blog that I can see how it applies. This was a clean install and setting of the target a few days ago, so whatever is the issue might be caused by the install/target platform? I haven't, to my knowledge, changed anything, and the tests run from Maven command line. I can run regular (not plugin) JUnit tests.

**Comment by crapo** [comment]
Didn't mean to close it, wrong button.

**Comment by crapo** [comment]
If I look at installation details, org.eclipse.pde.junit.runtime 3.5.7 is listed on the plugins tab.

**Comment by kittaakos** [comment]
Please check the `Main` tab too. Do you see the same as I have? If no, can you please alter your launch config to run the test as a product instead of an application?

![Screen Shot 2020-04-01 at 13 10 56](https://user-images.githubusercontent.com/1405703/78130914-72126000-741a-11ea-833d-8b5c65d88c6a.jpg)

**Comment by crapo** [comment]
Looks identical except my Execution environment is "JavaSE-1.8 (jdk1.8.0_241)"

**Comment by crapo** [comment]
If I click on Show Command Line on that tab I have this:
C:\Program Files\Java\jdk1.8.0_241\bin\javaw.exe -ea -Declipse.pde.launch=true "-Declipse.p2.data.area=@config.dir\p2" -Dfile.encoding=UTF-8 -classpath "C:\sadl\ws\.metadata\.plugins\org.eclipse.pde.core\.bundle_pool\plugins\org.eclipse.equinox.launcher_1.5.200.v20180922-1751.jar" org.eclipse.equinox.launcher.Main -os win32 -ws win32 -arch x86_64 -nl en_US -consoleLog -version 3 -port 63296 -testLoaderClass org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader -loaderpluginname org.eclipse.jdt.junit4.runtime -test com.ge.research.sadl.ui.tests.SadlModelArticleUITest:testCRule_02 -application org.eclipse.pde.junit.runtime.uitestapplication -product org.eclipse.platform.ide -data "C:\sadl\ws/../junit-workspace" -configuration file:C:/sadl/ws/.metadata/.plugins/org.eclipse.pde.core/pde-junit/ -dev file:C:/sadl/ws/.metadata/.plugins/org.eclipse.pde.core/pde-junit/dev.properties -os win32 -ws win32 -arch x86_64 -nl en_US -consoleLog -testpluginname com.ge.research.sadl.ui.tests

**Comment by crapo** [comment]
If I look at the path specified in this command line, I see this:
![image](https://user-images.githubusercontent.com/1186278/78131691-796d4580-73e9-11ea-995e-ffe476eb0caf.png)

**Comment by kittaakos** [comment]
Sorry, I have no idea what's causing the problem on your side, but I am available for a call if you want to figure it out via a remote-debug session.

**Comment by crapo** [comment]
Yes, please! I'll set up a Skype meeting. Is now a good time?

**Comment by kittaakos** [comment]
> Is now a good time?

Sure, please send the link.

**Comment by crapo** [comment]
https://meet.lync.com/gecompany/crapo/LDRG7CL6

**Comment by crapo** [comment]
I get the same behavior on my laptop. I conclude that I have not tried to run a UI test since moving to Eclipse 2020-03.

**Comment by kittaakos** [comment]
> I get the same behavior on my laptop.
> Eclipse 2020-03.

Same error here with the latest Eclipse; I will figure out something.

**Comment by kittaakos** [comment]
So it turned out, the JDT feature we use in the target platform is quite old.

https://github.com/crapo/sadlos2/blob/ff4d4767b21dbbf547b89ac6cfa3bf4da9e8e57d/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.target/com.ge.research.sadl.target.target#L24

The `org.eclipse.jdt.junit.runtime` plug-in has a version of `3.4.900.v20181012-1045`. This does not satisfy the `Require-Bundle: org.eclipse.jdt.junit.runtime; bundle-version="[3.5.0,4.0.0)` constraint.

You can verify it by searching for artifacts (<kbd>Ctrl/Cmd</kbd>+<kbd>Shift</kbd>+<kbd>A</kbd>) and search for `org.eclipse.jdt.junit.runtime`.

![Screen Shot 2020-04-01 at 16 38 51](https://user-images.githubusercontent.com/1405703/78150414-8fa1f280-7437-11ea-9600-a14146f1f190.jpg)

The bad news is that I do not see a solution for an old JDT in the target platform but new in the dev Eclipse, the good news is that there is a workaround. You can update the JDT and Eclipse SDK dependencies without bumping up Xtext:

```diff
diff --git a/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.target/com.ge.research.sadl.target.target b/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.target/com.ge.research.sadl.target.target
index 573154e4..ebf297b5 100644
--- a/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.target/com.ge.research.sadl.target.target
+++ b/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.target/com.ge.research.sadl.target.target
@@ -21,10 +21,10 @@
 <repository location="http://download.eclipse.org/lsp4j/updates/releases/"/>
 </location>
        <location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
-               <unit id="org.eclipse.jdt.feature.group" version="3.16.0.v20181206-1038"/>
-               <unit id="org.eclipse.platform.feature.group" version="4.10.0.v20181206-0815"/>
-               <unit id="org.eclipse.platform.source.feature.group" version="4.10.0.v20181206-0815"/>
-               <repository location="https://download.eclipse.org/releases/2018-12/"/>
+               <unit id="org.eclipse.platform.feature.group" version="4.15.0.v20200305-0155"/>
+               <unit id="org.eclipse.platform.source.feature.group" version="4.15.0.v20200305-0155"/>
+               <unit id="org.eclipse.jdt.feature.group" version="3.18.300.v20200305-0155"/>
+               <repository location="https://download.eclipse.org/releases/2020-03/"/>
        </location>
        <location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
                <unit id="org.eclipse.emf.sdk.feature.group" version="2.16.0.v20181206-1055"/>
```

If you apply this change and reload the target platform, it works. I have verified it locally.

**Comment by crapo** [comment]
fabulous!! Thank you. I'll make that change.

**Comment by kittaakos** [comment]
@crapo, please let me know if the proposed workaround does not work either. Thank you!

**Comment by kittaakos** [comment]
> fabulous!! Thank you. I'll make that change.

We posted at the same time. Great! I was not aware of this limitation of 2020-03 😕

**Comment by crapo** [comment]
That fixes the issue. Will this have any affect on the update created and the versions of Eclipse with which it is compatible?

**Comment by kittaakos** [comment]
> update created

I assume you're referring to p2.

> and the versions of Eclipse with which it is compatible?

Very good point; I or someone else has to verify it. If it is me, let me know.

**Comment by kittaakos** [comment]
@crapo, have you pushed the [proposed TP changes](https://github.com/crapo/sadlos2/issues/414#issuecomment-607291911) to the remote branch? My JUnit plug-in tests fail locally.

**Comment by kittaakos** [comment]
> have you pushed

It seems no. I am going to include it in #416.
