### ISSUE TITLE
docker details and options link broken

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#434]
@kittaakos , at [https://hub.docker.com/r/theiaide/sadl](https://hub.docker.com/r/theiaide/sadl) there is a link
[here](https://github.com/theia-ide/theia-apps/blob/master/theia-sadl-docker/README.md) that is broken. Do you know where this should point?

**Comment by kittaakos** [comment]
Now it points to here: https://github.com/crapo/sadlos2/blob/development/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/sadl-extension/README.md
