### ISSUE TITLE
(Inverse) Functional properties no longer supported?

### ISSUE THREAD

**Issue by glguy** [SemanticApplicationDesignLanguage/sadl#449]
I can't get functional or inverse functional properties to work in the latest release of SADL. I thought this syntax was accepted in a previous version I'd used. Now I get Unhandled SadlProperty expression*.

Is this working as intended?

```
uri "http://glguy.net/sadl/demo".

C is a class.
D is a class.
p describes C with a single value of type D.
p has a single subject.
p has a single value.
```

**Comment by crapo** [comment]
@glguy, you are right. Those have fallen through a crack. The statement "p describes C with a single value of type D." does make "p" a functional property in the OWL translation, but of course doesn't allow this to be stated without a range. Will add processing of the last two statements. Is there any urgency WRT to this omission?

**Comment by glguy** [comment]
@crapo No, this issue isn't urgent for my use-case. I'll just stick to using `with a single value` for the functional case and avoid inverse functional properties by defining functional ones in the other direction.

My goal is to learn as much about SADL and its syntax and capabilities as it is the language we're using to express an ontology of software systems, and in the course of developing my understanding of the correspondence between the SADL and generated OWL I've run into a couple of minor things like this. If there are things we can't express in SADL we can alway fall back to expressing them in OWL for now.

I have a follow-up question on `with a single value` making `p` functional. I see that it generates a cardinality restriction on the particular class, but that doesn't tell us that `p` is functional itself, right? Consider this example

```
uri "http://glguy.net/sadl/demo".

C is a class.
D is a class.
p describes C with a single value of type string.
p describes D with values of type string.
```

**Comment by crapo** [comment]
@glguy , I was wrong in what I said above. In SADL Version 2 it used to be (I'm still going by memory here) that "p ... with a single value of ..." translated to p being an owl:FunctionalProperty as sell as a cardinality restriction. That didn't seem to be defensible so in SADL Version 3 it just creates the cardinality restriction and if you want to make it an owl:FunctionalProperty you have to say "p has a single value.". I'm sure that's what you were seeing in the OWL translation.

I've fixed the missing implementation of "p has a single value." and of "p has a single subject.". This will be in the next release, which will include a bunch of minor bug fixes, sometime this coming week.

**Comment by crapo** [comment]
fixed in today's release.
