### ISSUE TITLE
Downloading external models in WebSADL

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#459]
@kittaakos , I'm trying to download external OWL models in WebSADL. I'm using the TestSadl3Ide sample project, which is at ...sadlos2/sadl3/Examples. TestSadl3Ide contains the file "externalmodels.url" with a couple of URLs in it. I thought that selecting SADL -> Download External Models would cause the download to occur but instead I get the notification "Only external model definitions can be used to download external OWL models." 

I kind of expected an error on http; URLs, since the firewall would object. I also tried using a file: URL, having placed the OWL file in the location setup as the "/project/home" in the docker container. Same notification.

Any idea what I'm doing wrong?

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/461
