### ISSUE TITLE
Rename Symbol in WebSADL does not appear to work

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#460]
@kittaakos , given model A.sadl defining Shape and B.sadl defining Circle (Circle is a type of Shape.), if I select Shape and ask to "Rename Symbol" on the popup menu, nothing happens. In the console window where the docker image was started "root Info NoResult." is displayed.

BTW, what does "Change All Occurrences" on the popup menu mean?

**Comment by kittaakos** [comment]
> nothing happens

Rename/refactoring [was implemented](https://github.com/crapo/sadlos2/issues/415) for the Eclipse IDE only with [an old, `2.14` version of Xtext](https://github.com/crapo/sadlos2/blob/0af9f6369421322700a4574d4a5b56b8d8d6d41a/sadl3/com.ge.research.sadl.parent/pom.xml#L11).

**Comment by crapo** [comment]
So "Rename Symbol" would normally be the right menu item for the renaming, but the implementation you reference was Eclipse-specific, if I understand. Implementing renaming of resources in WebSADL would be an entirely independent effort? How much effort would it take? And what is the "Change All Occurrences" on the menu mean?

**Comment by kittaakos** [comment]
> So "Rename Symbol" would normally be the right menu item for the renaming, but the implementation you reference was Eclipse-specific, if I understand.

Yes.

> mplementing renaming of resources in WebSADL would be an entirely independent effort?

Normally, no. It should be the same but we had to highly customize the rename/refactoring for ASKE to not insert conversation during the refactoring. (https://github.com/GEGlobalResearch/DARPA-ASKE-TA1/issues/68#issuecomment-589028359)

> How much effort would it take?

I have to spend an hour or so to be able to give a better estimate.

> And what is the "Change All Occurrences" on the menu mean?

It's pure free-text replace. It has nothing to do with the SADL-specific language features.

**Comment by kittaakos** [comment]
> > How much effort would it take?
> 
> I have to spend an hour or so to be able to give a better estimate.

@crapo, let me know if I should investigate it.

**Comment by crapo** [comment]
Yes, please investigate and let me know how much effort it would take to have renaming of concepts in WebSADL.

**Comment by kittaakos** [comment]
I've looked into the required changes; it does not seem to be a trivial task. In a nutshell; the LSP-based rename refactoring works with the change-serializer under the hood. It converts EMF attribute changes to text changes. The default Xtext implementation relies on the `name` attribute of the EObject. For the SADL resources, we have a completely different construct. The definition of the SADL resource refers to itself with an Xtext cross-ref:

https://github.com/crapo/sadlos2/blob/635f85ab8197a91d52407367c36da213a6e6cd1f/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/SADL.xtext#L448-L450

The default implementation provided by Xtext won't work for use as is. If we want to support rename/refactoring in the web version too, we have to add a custom implementation to support the SADL resources and make the Eclipse IDE version to use the LSP version. The required work would easily take one or two days. Let me know if we need this.

**Comment by kittaakos** [comment]
I have pushed a prototype to https://github.com/crapo/sadlos2/pull/463

![screencast 2020-06-15 10-43-12](https://user-images.githubusercontent.com/1405703/84637149-a5cb3500-aef5-11ea-8b60-81ed5f5e5b32.gif)

**Comment by crapo** [comment]
@kittaakos , I've looked at the PR. I'm a little confused. Does this prototype refactoring work for both Eclipse and Web SADL? You said it could easily take 2 or 3 days, so there's lots more to do or it is mostly done and took less time than you expected?

**Comment by kittaakos** [comment]
> work for both Eclipse and Web SADL

No, it is for the web only. It's a messy prototype.

----

> You said it could easily take 2 or 3 days,

😃 Well, I said one or two days. See [my comment](https://github.com/crapo/sadlos2/issues/460#issuecomment-643943481):

> The required work would easily take one or two days.

----

> so there's lots more to do or it is mostly done and took less time than you expected?

It is just a prototype to show it works. As I said, it takes a day or two to support it. The followings are missing:
 - handle name collision,
 - escape identifiers,
 - single-source the web and Eclipse, and
 - add tests and more tests.

**Comment by crapo** [comment]
Then let's go for it! Thanks for a quick prototype. Do I understand correctly that the results will be code common to the Ecllipse-based and Web SADL?

**Comment by kittaakos** [comment]
> Then let's go for it!

👍 I believe I can deliver the PR by the begging of the next week.

> Do I understand correctly that the results will be code common to the Ecllipse-based and Web SADL?

Yes. I do my best to reuse most of the code between the web and the Eclipse version. The only issue I can see is the Eclipse version for ASKE; we had to disable the conversation during the validation phase. I am going to test this first, and if there is a technical obstacle, I'll let you know.
