### ISSUE TITLE
WebSADL: what is meaning of coloring in Explorer?

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#462]
@kittaakos , I created a new Workspace. Created new Project. Created new .sadl file in project. Uploaded a different .sadl file using "Upload Files..." from the context menu. Result shows WS, project, and the uploaded file in yellow font. What does this mean?
![image](https://user-images.githubusercontent.com/1186278/84424986-d9a11480-abee-11ea-8b36-da67cb6b0ffd.png)

**Comment by kittaakos** [comment]
> What does this mean?

It means there is a validation warning in that file. The validation decorator is propagated up to the container folder just as in the Eclipse IDE. For instance, if the file `/path/to/file.sadl` has a warning, you will see a marker on `path` and  `to` folders, plus on the `file.sadl`. Same for an error:

![screencast 2020-06-12 08-38-02](https://user-images.githubusercontent.com/1405703/84473837-06eed080-ac8a-11ea-9c8b-69c3099ac512.gif)

You can disable it via `File` > `Settings` > `Open Preferenes`:
![Screen Shot 2020-06-12 at 08 37 14](https://user-images.githubusercontent.com/1405703/84473890-21c14500-ac8a-11ea-8a15-749ba7c1622f.jpg)

Then set `decorations.enabled` to `false`:
![Screen Shot 2020-06-12 at 08 37 40](https://user-images.githubusercontent.com/1405703/84473950-3c93b980-ac8a-11ea-8229-3c85bcf5a4bc.jpg)

You can see the same error from the Problems view (`View` > `Problems` from the menu):
![Screen Shot 2020-06-12 at 08 55 19](https://user-images.githubusercontent.com/1405703/84474060-7cf33780-ac8a-11ea-8778-75fa60a78375.jpg)


I hope this helps.
