### ISSUE TITLE
Unable to get ResourceSet unless menu is opened

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#472]
@kittaakos , this is an issue with the SADL Gear icon and dropdown menu. If I mouse over the icon it says "Test Model". However, if I click on the icon rather than getting the dropdown mneu and selecting "Test Model" the resourceSetProvider at line 387 in SadlActionHandler is null. I don't know how to resolve this. This is work to PO for ARCOS.

**Comment by kittaakos** [comment]
I see; the plug-in configuration was incomplete. We have to prefix the default handler with the class that will do the dependency injection. Otherwise, the fields will be `null`. Here is the PR: https://github.com/crapo/sadlos2/pull/473
