### ISSUE TITLE
testRenameDecl_MultiFile test failure

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#475]
@kittaakos , after merging the renaming PR (but I don't know if it is the cause, testRenameDecl_MultiFile in SadlRenameTest fails. It looks to me like the renaming succeeded but the output has the files in a different order than expected, but I'm not sure I understand the test. I've ignored the test for the moment.

**Comment by kittaakos** [comment]
OK, I see the issue. Thank you for letting me no. Fortunately, it's a problem with the test assertion and not the behavior. See the error message from the CI:
```
[ERROR]   SadlRenameTest.testRenameDecl_MultiFile:203->testRename:289->assertEquals:233->AbstractLanguageServerTest.assertEquals:1398 expected:<changes :
    [Other.sadl : Bar [[2, 11] .. [2, 14]]
    TestMe.sadl : Bar [[1, 0] .. [1, 3]]]
documentChanges :...> but was:<changes :
    [TestMe.sadl : Bar [[1, 0] .. [1, 3]]
    Other.sadl : Bar [[2, 11] .. [2, 14]]]
documentChanges :...>
[INFO] 
```
The changeset is correct, the changed ranges also look good, but the order of the changed resources is the difference. I will adjust the assertions.

**Comment by kittaakos** [comment]
PR: https://github.com/crapo/sadlos2/pull/476
