### ISSUE TITLE
Incrementing SADL Version

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#479]
@kittaakos , it isn't clear to us how to update the SADL version. The parent version is in every project pom under parent. I'm not sure where else an update is required. Would you be so kind as to write a set of instructions for incrementing the SADL Version number? I've just updated to Jena 3.16.0 and that opens a lot of new functionality so a version bump seems appropriate.

**Comment by kittaakos** [comment]
> Would you be so kind as to write a set of instructions for incrementing the SADL Version number?

Can you please use [this](https://github.com/crapo/sadlos2/pull/419/commits/1416537ae063902d1f519caaa86350c2b70ac754) commit as a reference?

One has to update the version:
 - in the parent POM,
 - each POM per project,
 - `MANIFEST.MF` per project,
 - and in the SADL feature.

Note, updating the `category.xml` for the p2 is not required as it is set to `0.0.0`.

If it's not clear how to proceed, I can do the update or I can review your changes if you're unsure.

**Comment by crapo** [comment]
This is done on the Jena3.16 branch.
