### ISSUE TITLE
Flag warning when "note" added at point other than in declaration

### ISSUE THREAD

**Issue by AbhaMoitra** [SemanticApplicationDesignLanguage/sadl#482]
If a "note" is added at a point other than in a declaration then the "note" text does not appear in tooltip when hovering over a reference to that entity / property.

**Comment by crapo** [comment]
@AbhaMoitra , one could relax the constraint so that annotations (notes, alias) could be specified on references as long as they are in the same namespace (in the same .sadl file). Thoughts?

**Comment by AbhaMoitra** [comment]
I will leave that up to you. For RACK, all the "note"have been moved to declaration.

**Comment by crapo** [comment]
Leaving at simpler solution of allowing only in definitions. Available in V3.4.0.

**Comment by crapo** [comment]
Actually, it's an error. And it occurs only if the annotation is in different namespace (another .sadl file) than the definition, since it is hard for people to tell sometimes which is the definition.
