### ISSUE TITLE
Flag use of ambiguous properties in a SPARQL query

### ISSUE THREAD

**Issue by AbhaMoitra** [SemanticApplicationDesignLanguage/sadl#484]
Consider the SPARQL query 

  Ask: "select distinct ?rq ?sId  where
       {  ?rq <rdf:type> <REQUIREMENT>
        . ?REQUIREMENT <satisfies> ?sId
       }".
where there are definitions of "satisfies" that are imported, so the use of "<satisfies>" is ambiguous. Can we flag such ambiguous usage with a warning.

**Comment by crapo** [comment]
SPARQL queries are now "prepared" by expanding incomplete concept references (either just name of qname) and ambiguous names are detected and reported. Test case added.
