### ISSUE TITLE
Cannot import source code into Eclipse

### ISSUE THREAD

**Issue by kittaakos** [SemanticApplicationDesignLanguage/sadl#493]
I cannot get rid of the compiler errors in Eclipse. I did the same as always:
 - Clone the repo,
 - `mvn clean`,
 - `mvn install -U`,
 - Import SADL as an existing Maven project,
 - Set the target platform,
 - Do `Maven` > `Update Projects...` > `Force Update Snapshots/Releases`,
 - Clean all projects.

Related https://github.com/crapo/sadlos2/commit/06fca89483f656f3f8480ad7c7ac3ddf07b022df?

CC: @crapo, @tuxji

**Comment by kittaakos** [comment]
> * Import SADL as an existing Maven project,

Lesson learned: the project has to be exported as `General` > `Existing Projects into Workspace` and **not** an existing Maven project.

**Comment by crapo** [comment]
@kittaakos , I don't understand the lesson learned. We're talking about exporting the parent project? one of the children projects? I guess I wasn't aware that they got exported as I've only seen it from the perspective of cloning the repo and importing as Maven projects.

**Comment by crapo** [comment]
@kittaakos , I'm thinking that the confusion is because you mean "the project has to be **imported** as ...", not "... has to be **exported** as...". Is that correct?

**Comment by kittaakos** [comment]
> the project has to be **imported** as ...", not "... has to be **exported** as...". Is that correct?

Oh, yes you're right. 😄 Sorry for the confusion.

**Comment by crapo** [comment]
I am doubtful of the correctness of this lesson learned. I just tried importing as regular projects and it didn't ask about the Maven plugin connectors and it didn't ask about installing Tycho Project Configurators. I ended up with all kinds of errors when I was done. I deleted the projects and the WS .metadata and tried it importing as Maven projects and it worked perfectly.
