### ISSUE TITLE
strConcat - original signature errors

### ISSUE THREAD

**Issue by foleycw** [SemanticApplicationDesignLanguage/sadl#496]
str1 = strConcat("CoatDiffer: Coating is not the same. Source: ",sourceCoating,", Destination: ", destCoating)

Getting wrong error for number of arguments even after changing function signature to "--" to accept any number of arguments. Signature should be "(string X, ...)"  

Original signature "(string X, string Y)"  was incorrect.

**Comment by crapo** [comment]
Fixed signature content from JenaReasonerPlugin, added test case to ExtendedIFTests and corrected content in SadlTestHelper for building functions.
