### ISSUE TITLE
Writing RDF Binary format requires IFileSystemAccessExtension3

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#515]
@kittaakos , one of the new OWL formats supported by Jena is RDF Binary, which requires that the model processor onGenerate method write the file as binary, not text. (See https://lists.apache.org/list.html?users@jena.apache.org:lte=1M:crapo.) Is there a way to cause onGenerate to get an IFileSystemAccess that supports binary output? Other options?

**Comment by kittaakos** [comment]
> onGenerate to get an IFileSystemAccess

`onGenerate` gets an `IFileSystemAccess2`:

https://github.com/crapo/sadlos2/blob/fa98426fa22fa3e868ad87009676d752afb7a522/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl.jena/src/com/ge/research/sadl/jena/JenaBasedSadlModelProcessor.java#L524

[`IFileSystemAccess2`](https://github.com/eclipse/xtext-core/blob/ee7cf5f1968bbd4400d878e4906eccda51ef03ef/org.eclipse.xtext/src/org/eclipse/xtext/generator/IFileSystemAccess2.java#L24) is-a [`IFileSystemAccessExtension3`](https://github.com/eclipse/xtext-core/blob/ee7cf5f1968bbd4400d878e4906eccda51ef03ef/org.eclipse.xtext/src/org/eclipse/xtext/generator/IFileSystemAccessExtension3.java#L21). I think it has the requied API for binray serialization:
```java
	/**
	 * Writes binary data to disk. For writing text, it is recommended to use
	 * {@link IFileSystemAccess#generateFile(String, String, CharSequence)}
	 */
	void generateFile(String fileName, String outputCfgName, InputStream content) throws RuntimeIOException;
```

**Comment by kittaakos** [comment]
Did this 👆 help, @crapo?

**Comment by crapo** [comment]
@kittaakos , sorry to be slow. I've been out this week. Yes, looks like I just need to call the right onGenerate method to output binary. I should have looked more closely. Thanks!!! (I'll close this when I've proven that this solves my problem.)

**Comment by crapo** [comment]
I couldn't figure out any way to get the InputStream that the IFileSystemAccess2 wanted to write binary from the Jena OntModel. Finally just used the OwlModel folder path and the OWL filename to write the output, if in RDF-THRIFT format, using the Jena RDFDataMgr.
