### ISSUE TITLE
Datatype restrictions missing type on range values

### ISSUE THREAD

**Issue by kquick** [SemanticApplicationDesignLanguage/sadl#516]
When creating a datatype restriction (e.g. https://github.com/ge-high-assurance/RACK/blob/31229b8803068d92c9b971647a7172f6611722f8/RACK-Ontology/OwlModels/CONFIDENCE.owl#L24-L25), the emitted OWL representation are lacking the `rdfs:datatype` on the range value specifications shown here: https://github.com/ge-high-assurance/RACK/blob/31229b8803068d92c9b971647a7172f6611722f8/RACK-Ontology/OwlModels/CONFIDENCE.owl#L24-L25

My expectation would be that these would be emitted as:

            <xsd:maxInclusive rdf:datatype="http://www.w3.org/2001/XMLSchema#float">1</xsd:maxInclusive>
            <xsd:minInclusive rdf:datatype="http://www.w3.org/2001/XMLSchema#float">0</xsd:minInclusive>

**Comment by kquick** [comment]
Sorry, wrong link for the SADL source above, it should be: https://github.com/ge-high-assurance/RACK/blob/31229b8803068d92c9b971647a7172f6611722f8/RACK-Ontology/ontology/CONFIDENCE.sadl#L13

**Comment by crapo** [comment]
@kquick , where did you get the idea that that is the expected OWL equivalent? The parent type of the extended rdfs:Datatype is given in the owl:equivalentClass by the owl:onDatatype property.  (I don't know how to retain the correct formatting in the snippet below.)

  <rdfs:Datatype rdf:ID="Probabilitiy">
    <owl:equivalentClass>
      <rdfs:Datatype>
        <owl:withRestrictions rdf:parseType="Collection">
          <rdf:Description>
            <xsd:maxInclusive>1</xsd:maxInclusive>
            <xsd:minInclusive>0</xsd:minInclusive>
          </rdf:Description>
        </owl:withRestrictions>
        <owl:onDatatype rdf:resource="http://www.w3.org/2001/XMLSchema#float"/>
      </rdfs:Datatype>
    </owl:equivalentClass>
  </rdfs:Datatype>

The xsd restrictions are within the owl:withRestrictions property and can be a whole collection of restrictions. To the best of my knowledge this is the correct formulation. See https://www.w3.org/TR/owl2-quick-reference/#Data_Ranges.

**Comment by kquick** [comment]
My expectation was based on two elements:

1) In working with OWL/RDF triples generated via SWI Prolog, the restriction values had accompanying `rdf:datatype` specifications, and when that `rdf:datatype` specification was not included, the values were interpreted as strings.

2) My reading of section 7.5 "Data Restrictions" (in https://www.w3.org/TR/2012/REC-owl2-syntax-20121211/#Datatype_Restrictions) indicated `n` pairs of `(F_i, lt_i)`, where `lt_i` are referred to as literals, and in section 5.7 of that same document it defines literals as using the `lexical^^datatypeURI` form, which seems to correspond to usage of the `rdf:datatype` in OWL/RDF syntax.

Admittedly, this is (a) a very complex specification that I could easily be misunderstanding, (b) the SWI Prolog version is simply another implementation and not a reference standard, and (c) the specification also seems to imply that any *lexical value* representation has an *actual value* comprised of interpretation of the lexical value as appropriate to the target type, so I suppose a dynamic typing approach is equally valid at this point.

**Comment by crapo** [comment]
Interesting. I'll look into this more, but just to be clear, the SADL implementation is not ambiguous nor a dynamic typing approach I don't believe because the type (float) is clearly indicated by the owl:onDatatype property, which is float.

**Comment by crapo** [comment]
@kquick , this is clearer to me now. You are looking at OWL 2 documentation. SADL uses Jena and hence is primarily using OWL 1 with limited OWL 2 support. Hence the syntax will be different. However, the type of the range limits can be typed so I'll look at doing so. That way their type would not have to be inferred from the owl:onDatatype value.

**Comment by crapo** [comment]
@kquick , I've changed the code to include the rdf:datatype of the minInclusive and maxInclusive values. Good call! Thanks for following through on this. This will be in the next release. Is there any urgency for this to be released right away?

**Comment by kquick** [comment]
Thank you for taking a look, @crapo, I hadn't considered that it was an OWL version-related change.  There's no urgency on this, so add it in to a release whenever it's convenient, and thanks for looking into this with me.

I don't know your policy on closing issues (if you close when the code is updated, or when there is a release), but please feel fre to close this issue when you are ready.

**Comment by crapo** [comment]
This will be in the next release.
