### ISSUE TITLE
Move repo to an organizaton

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#522]
@kthoms , can you please delete you "sadl" repo? I'm trying to reduce the name conflicts. Thanks!!

**Comment by kthoms** [comment]
Done.

**Comment by GEGlobalResearch** [comment]
Thanks!

**Comment by crapo** [comment]
@kittaakos , please accept invitation to new organization. Otherwise assignments will be lost when I move my personal repo to the new organization.

**Comment by crapo** [comment]
@kittaakos , also I'm not sure if any thing in the CI integrations will break. Will you be around next week to help repair if they do?

**Comment by kittaakos** [comment]
> Will you be around next week to help repair if they do?

Unfortunately, I don't. I am starting my two weeks vacation today.

I looked into the build configs now, they do not reference the repository, so if you do not change anything in the folder structure but just move the repo, we do not have to change the configs for the CI. However, someone might have to re-register the new repo link on AppVeyor and Travis CI.

**Comment by kittaakos** [comment]
> Will you be around next week to help repair if they do?

@crapo, let me know if you still need assistance with the CIs.

**Comment by crapo** [comment]
Hi @kittaakos , welcome back! I hope you had a great vacation.
I waited until you are back to do the change. I will do it in the next couple of days. Also, I anticipate approval so that you can upgrade to newer APIs in Xtext 2.22.

**Comment by crapo** [comment]
Completed successfully.

**Comment by kittaakos** [comment]
FYI: I do not see the build running for the PRs. For example https://github.com/SemanticApplicationDesignLanguage/sadl/pull/531.

**Comment by crapo** [comment]
@kittaakos , @agabaldon : I guess more needs to be done here. Currently the CI runs (or doesn't run as it should?) on accounts on appveyor.com and travis-ci.org that are in my name. I suppose those could stay so that I can see results of CI, but we should also create accounts for GE. Does that make sense? 

Also, I don't understand your last comment, @kittaakos . I manually ran on appveyor.com just now and it was successful. I checked the settings in github and they are the same as they were before moving to the organization. Not sure what needs to be done....

**Comment by kittaakos** [comment]
> Does that make sense?

It's a must, I think. Once we have the new account, we have to add it to npmjs and docker as a collaborator. The same way as we did with your personal account, @crapo.

npmjs:
![Screen Shot 2020-10-19 at 15 56 58](https://user-images.githubusercontent.com/1405703/96461262-72dada00-1224-11eb-8e08-a6ff509b47c6.jpg)

Docker:
![Screen Shot 2020-10-19 at 16 00 01](https://user-images.githubusercontent.com/1405703/96461241-6f475300-1224-11eb-8ffb-420197d2b2dd.jpg)


Maybe it would be better to set up the CI to use GitHub Actions only, instead of the two CI services (AppVeyor, and Travis).

> Also, I don't understand your last comment, @kittaakos .

The build must run for each PR. It does not run now.
PR after the move:
![Screen Shot 2020-10-19 at 16 03 14](https://user-images.githubusercontent.com/1405703/96461579-d533da80-1224-11eb-9ab3-3891a7af76b6.jpg)

PR before the move:
![Screen Shot 2020-10-19 at 16 03 41](https://user-images.githubusercontent.com/1405703/96461593-dbc25200-1224-11eb-91d3-ef4c10e1b57e.jpg)

**Comment by crapo** [comment]
@kittaakos , if I understand correctly, we can do CI entirely within github now. Is there a reason why we would want to set up accounts and do it on ci.appveyor.com and travis-ci.org? What about the automatic building of new docker images for hub.docker.com? Are those independent of the CI WebHooks? @tuxji , do you have an opinion on the best way to do CI now that SADL is moved to an organization?

**Comment by tuxji** [comment]
I agree with @kittaakos that we could run the CI entirely within GitHub and that it'd probably be better to do it that way so that you don't have to set up two other CI services (AppVeyor, Travis) all over again.  I hope Akos can do it since I have a lot to do the next two weeks, though.

**Comment by kittaakos** [comment]
> Is there a reason why we would want to set up accounts and do it on ci.appveyor.com and travis-ci.org?

No, I would go with GH Actions only.
We had to set up a Travis and AppVeyor account/CI in the past because Travis did not support the Windows image. So we needed AppVeyor for running the build on Windows and Travis for the Linux version.

> Are those independent of the CI WebHooks?

Yes.

**Comment by kittaakos** [comment]
> we can do CI entirely within github now

It's free for opensource, but please check https://github.com/pricing.
If we decide to use it, here are the steps for adding the secrets: https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository

**Comment by kittaakos** [comment]
@crapo, do you want me to work on this?

**Comment by crapo** [comment]
Not sure, will get this answered and let you know.

**Comment by GEGlobalResearch** [comment]
@kittaakos , @tuxji will do this task but will require some support from you to understand what the CI was doing before. Please talk to each other to resolve any questions. Thanks!

**Comment by kittaakos** [comment]
> will do this task

As you wish, thanks for the heads-up.

> understand what the CI was doing before

1. Build the SADL p2 and the LS:
https://github.com/SemanticApplicationDesignLanguage/sadl/blob/7c246b2f8e85642126587bad6ab3372b64373da0/.travis.yml#L22-L23

2. Build the Theia app. Note, it uses the LS that we build in `1.`:
https://github.com/SemanticApplicationDesignLanguage/sadl/blob/7c246b2f8e85642126587bad6ab3372b64373da0/.travis.yml#L39

3. Publish to npmjs.com:
https://github.com/SemanticApplicationDesignLanguage/sadl/blob/7c246b2f8e85642126587bad6ab3372b64373da0/.travis.yml#L44

4. Build the Docker image:
https://github.com/SemanticApplicationDesignLanguage/sadl/blob/7c246b2f8e85642126587bad6ab3372b64373da0/.travis.yml#L61

5. Publish the Docker image:
https://github.com/SemanticApplicationDesignLanguage/sadl/blob/7c246b2f8e85642126587bad6ab3372b64373da0/.travis.yml#L66

I hope this helps.

**Comment by tuxji** [comment]
Thanks, that helps.

@kittaakos - if you know what the values of the following secrets are, will you please store corresponding GitHub secrets in the sadlos2 repository to make them available to the GitHub actions as well?

- DOCKER_USERNAME
- DOCKER_PASSWORD (or DOCKER_TOKEN which might be preferable)
- NPM_AUTH_TOKEN

**Comment by kittaakos** [comment]
> will you please store corresponding GitHub secrets in the sadlos2 repository to make them available to the GitHub actions as well?

I do not know them. @crapo configured it with his personal credentials.

**Comment by crapo** [comment]
@kittaakos , @tuxji , do we need an organizational account on docker.com? Or maybe a GEGlobalResearch account? There is theaide organization with a theaide/sadl repository. How do transition this so that it doesn't involve my personal account?

**Comment by kittaakos** [comment]
> How do transition this so that it doesn't involve my personal account?

You register an account for npmjs and Docker and we add it as a collaborator. See https://github.com/SemanticApplicationDesignLanguage/sadl/issues/522#issuecomment-712180709

**Comment by crapo** [comment]
Adding @tuxji to assignees as he is completing the re-implementation of the CI.

**Comment by tuxji** [comment]
@kittaakos Where do we need to register a new organizational account?
- Docker Hub has already been done (https://hub.docker.com/orgs/sadl)
- npmjs too?

**Comment by kittaakos** [comment]
> * npmjs too?

Yes.

**Comment by tuxji** [comment]
@kittaakos I've created an individual account (tuxji) on npmjs.com and I've created an organization (sadl) in case we need one.  I see we're already using another organization (typefox-team) for publishing the npm package but can we add an organization (sadl) as a collaborator or will it have to be my individual account?  Either way, then I will create a new NPM_AUTH_TOKEN and save it as a GitHub secret (likewise DOCKER_USERNAME and DOCKER_TOKEN for pushing to the new sadl repository on Docker Hub).

**Comment by kittaakos** [comment]
> I've created an individual account (tuxji) on npmjs.com

👍 

> I've created an organization (sadl) in case we need one

Great. Yes, we need one.

> (typefox-team) for publishing the npm package but can we add an organization (sadl) as a collaborator or will it have to be my individual account?

I do not know. I guess, both works. It is up to you whether you need an individual or organization npmjs account.

> Either way, then I will create a new NPM_AUTH_TOKEN and save it as a GitHub secret (likewise DOCKER_USERNAME and DOCKER_TOKEN for pushing to the new sadl repository on Docker Hub).

Sounds good. Let me know when you have finalized both the npmjs and Docker accounts creation and the secrets are also configured. I will add the two new accounts as a contributor, we start the build, and hopefully, it will be green. 🤞

**Comment by crapo** [comment]
@tuxji , @kittaakos , do we have CI and WebSADL docker image generation working? If so then I think this can be closed.

**Comment by tuxji** [comment]
Yes, the CI workflow successfully generates the WebSADL docker image now.  We may want to write a CI release workflow that builds a SADL zip file and updates a SADL update site, but this issue can be closed and another issue created for that.
