### ISSUE TITLE
CSV import as OWL fails (possibly related to issue #530)

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#540]
Attempted to do an import from CSV file into OWL and it fails to generate an owl file. Console shows 
   javax/activation/DataSource
in red. I'm on MacOS with SADL release 3.4.1.202010211718 installed. 
@crapo was able to reproduce on Windows.

**Comment by crapo** [comment]
Still didn't have MANIFEST.MF files right. Needed to be exported from com.ge.research.jena (3rd party jars) and imported by all projects using but NOT as a Required-Bundle as that  referenced the javax.activation package in Eclipse, leading to duplicate resolutions.
