### ISSUE TITLE
SADL import templates issues

### ISSUE THREAD

**Issue by AbhaMoitra** [SemanticApplicationDesignLanguage/sadl#552]
Using SADL update dated 10/30/2020,  Java 11, eclipse DSL; I am able to run a project that imports CSV data using templates. However, when I use the template to import the CSV file as a SADL file I get an error. This issue can be replicated using the VERDICT-STEM project on GIT (https://github.com/ge-high-assurance/VERDICT/tree/master/tools/verdict-back-ends/STEM). Note that I do not have this issue when I use SADL version dated 10/21/2020.

**Comment by crapo** [comment]
@AbhaMoitra , what is the error exactly?

**Comment by AbhaMoitra** [comment]
@crapo I restarted eclipse and now I do not have any issues. Not sure what happened. I am closing this issue as I think it should not have been entered.
