### ISSUE TITLE
Unexpected error in SADL query

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#557]
From QS Tutorial, given "George is a Man." and "Man is a type of Person.":

Ask: select x where George is an x.

creates an unexpected error.

**Comment by crapo** [comment]
Issue seems a little more general than just a query. The rule 

`Rule sameThing: if George is an x then print("George is an ", x).`

also generated an error, although not quite the same. Note that in each case the declaration of "x" seems possibly wrong. Wouldn't the declaration of all variables in a query be in the where clause? And the declaration of all variables in a rule in the rule head?

**Comment by crapo** [comment]
@kittaakos , I think I've tracked this down to something that I don't understand. I've added a couple of tests to SadlLinkingTest, which I haven't pushed but I can put the essence here for a thought question and I'm hoping you can answer without resorting to actual code.
In the case that works, the SelectStatement is `"select <i> where [i] is a Foo" `
while for the case that does not work it is `"select <x> where MyFoo is an [x]"`.
The EObject hierarchy for the where clause is the same for both:
```
   BinaryOperation
        left: Name
        right: Declaration
             type: SadlSimpleTypeReference
                   type: SadlResource
```

It appears to me that the issue is this. In SADLScopeProvider doGetLocalVariableScope, there is a call to EcoreUtils2.getAllContents(expression, false).filter(SadlResource).filter(predicate) where expression is the SelectExpression, to get all of the SadlResources over which to iterate to potentially add to the scope map. It the first instance, this returns only "i", the SadlResource in the Name, the left of the BinaryOperation. In the second instance it returns only "MyFoo". Result: "i" is identified and added to scope in the first case but "x" is not identified and added to the scope in the second case.
Reason: getEObjectChildren(SadlSimpleTypeReference) always returns an empty list.
But, I have no idea why that would be the case. Can you shed any light?
@agabaldon , @weisenje : mentioning you here to make you aware of the question as this is indeed an interesting issue and one I've spent many hours trying to understand.

**Comment by crapo** [comment]
@kittaakos , @agabaldon , @weisenje : to make this explicit, I've pushed code branch GH-557 with a test added, SadlModelProcessorBasicsTest.testModelContents. The simple model is:
```
Person is a class.
Man is a type of Person.
George is a Man.
Ask: select x where George is an x.
```

Getting all contents:
```
		val cnts = sadlModel.allContents
		while (cnts.hasNext) {
			val el = cnts.next
			println(el.class.toString)
		}

```
Gives the following output. Note that the SadlResource which is the "type" of the SadlSimpleTypeReference is not found for each instance of SadlSimpleTypeReference in the tree iterator.

class com.ge.research.sadl.sADL.impl.SadlModelImpl
class com.ge.research.sadl.sADL.impl.SadlClassOrPropertyDeclarationImpl
class com.ge.research.sadl.sADL.impl.SadlResourceImpl
class com.ge.research.sadl.sADL.impl.SadlClassOrPropertyDeclarationImpl
class com.ge.research.sadl.sADL.impl.SadlResourceImpl
class com.ge.research.sadl.sADL.impl.**SadlSimpleTypeReferenceImpl**
class com.ge.research.sadl.sADL.impl.SadlInstanceImpl
class com.ge.research.sadl.sADL.impl.SadlResourceImpl
class com.ge.research.sadl.sADL.impl.**SadlSimpleTypeReferenceImpl**
class com.ge.research.sadl.sADL.impl.QueryStatementImpl
class com.ge.research.sadl.sADL.impl.SelectExpressionImpl
class com.ge.research.sadl.sADL.impl.SadlResourceImpl
class com.ge.research.sadl.sADL.impl.BinaryOperationImpl
class com.ge.research.sadl.sADL.impl.NameImpl
class com.ge.research.sadl.sADL.impl.DeclarationImpl
class com.ge.research.sadl.sADL.impl.**SadlSimpleTypeReferenceImpl**

**Comment by kittaakos** [comment]
I will take a look later today.

**Comment by kittaakos** [comment]
@crapo, I am not sure if I understood the request/question, so let's see.

Given your model:
```java
uri "http://sadl.org/gh557.sadl" alias gh557.

Person is a class.
Man is a type of Person.
George is a Man.

Ask: select x where George is an x.
```

Are you asking why a `SadlSimpleTypeReference` instance does not (EMF-)contain the `type` SADL resource? If so, it was always like this, it's a reference. See here:
https://github.com/SemanticApplicationDesignLanguage/sadl/blob/431df2fbaf3901969cfe6cfe10ded29e163ff8c0/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/SADL.xtext#L170

**Comment by crapo** [comment]
@kittaakos , thanks for looking at this. I thought it might be something like this but didn't know what exactly. So the allContents method return will not include the the actual SadlResource referenced, but I can, in doGetLocalVariableScope, when the SadlSimpleTypeReference is encountered give special handling to get the type SadlResource to make the scoping do the right thing. Does that make sense?

**Comment by kittaakos** [comment]
> So the allContents method return will not include the the actual SadlResource referenced

Correct.

> but I can, in doGetLocalVariableScope, when the SadlSimpleTypeReference is encountered give special handling to get the type SadlResource to make the scoping do the right thing. Does that make sense?

Yes, it absolutely makes sense. Please ping me if you need a review.

**Comment by crapo** [comment]
@kittaakos , when I check for expression content of type SadlSimpleTypeReference in method doGetLocalVariableScope and then call getType to get the SadlResource instance which is the type, it recursively comes back to the same, see image of call stack. So it doesn't appear to be quite that easy.... Suggestions?
![image](https://user-images.githubusercontent.com/1186278/101665750-62243480-3a1b-11eb-9566-0ddd6d246666.png)

**Comment by crapo** [comment]
Just to reiterate the bigger picture, in this particular case the SadlResource which is the type of the SadlSimpleTypeReference is variable and it is the declaration of the variable so I need to find it and add it to the scope as such.

**Comment by crapo** [comment]
I think the answer is that “.. is an x” can’t be the declaration of x as it’s an explicit reference to x, implying that x must be declared elsewhere. Therefore, although illogical from the query perspective, since the reference in "select x" is only to say which variables to return, this x has to be the declaration. The  reference in the where clause must be a reference. Type checking will have to find the appropriate reference to x in order to impute the type of x.

**Comment by crapo** [comment]
This was a tricky one in that the grammar defies the desired solution, which is that the variable x in a query like "select x where MyInstance is an x." is defined in the where. This is because the reference to x in "is an x" is just that--a reference to a SadlResource, not an actual SadlResource. Therefore the declaration is in the select but the type of x must be determined in the where. This is true in other cases besides queries. However, the implemented solution seems robust.
Ready to close when PR #596 is merged into development.

**Comment by crapo** [comment]
Merged, so closing.
