### ISSUE TITLE
First inference of a new or newly imported project

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#558]
If I create or import a new project and ask for inference (Test Model), the following error occurs. It no longer happens after I go into project properties, reasoner settings, and save. Missing configuration file?
`com.ge.research.sadl.reasoner.TranslationException: Invalid format: 
	at com.ge.research.sadl.model.SadlSerializationFormat.getRDFFormat(SadlSerializationFormat.java:64)
	at com.ge.research.sadl.ide.handlers.SadlRunInferenceHandler.run(SadlRunInferenceHandler.java:86)
	at com.ge.research.sadl.ide.handlers.SadlRunInferenceHandler.run(SadlRunInferenceHandler.java:78)
	at com.ge.research.sadl.ui.handlers.RunInference$1$1.run(RunInference.java:74)`

**Comment by crapo** [comment]
configuration.rdf file is there, so it isn't that. Also, just going into workspace preferences and setting a few things and saving resolves issue. No need to edit project properties.

**Comment by ymy530** [comment]
Hi Crapo, I am new to SADL and starting explore this tool today. I encountered exactly the issue you ran into. And you mentioned above that "just going into workspace preferences and setting a few things", can you please be more specific about the step you took to solve this issue? Many thanks in advance!
![Screen Shot 2020-11-06 at 4 55 34 PM](https://user-images.githubusercontent.com/17860388/98346416-e49e8a80-2050-11eb-964e-b007d668278a.png)

**Comment by crapo** [comment]
Type Checking Settings would be a possibility. Unless you want to be very exacting you might change to this:
![image](https://user-images.githubusercontent.com/1186278/98540232-9f01dd80-225b-11eb-8ad0-fb1e05a3d24c.png)

**Comment by ymy530** [comment]
Thanks！

**Comment by crapo** [comment]
PR for this fix has been merged into development branch. Will be in next release.
