### ISSUE TITLE
Alias in graphing when a project references another project

### ISSUE THREAD

**Issue by AbhaMoitra** [SemanticApplicationDesignLanguage/sadl#562]
Very minor issue: Consider project P2 that references project P1. The SADL files in P1 have aliases but when graphing project P2, the alias for P1 SADL files is not used in the graph. An example can be found with RACK-Ontology and Turnstile-Ontology in https://github.com/ge-high-assurance/RACK (this is now open project).

**Comment by crapo** [comment]
@AbhaMoitra , while looking at this I note that in CounterApplicationRequirementsSpec.sadl, lines 33 and 41, "mitigates" is ambiguous, which is an error. Presumably should be "Rq:mitigates"?

**Comment by crapo** [comment]
Note also that All.sadl does not have an alias.

**Comment by AbhaMoitra** [comment]
@crapo : I had noticed the error markings and we had put in a "hot fix" - maybe that got dropped somehow. I'll investigate. (These error markings are present in windows environment but were not visible in a Linux environment where this model extension was developed.) Thank you for pointing this out!

**Comment by crapo** [comment]
I observed the errors in a Linux environment. I don't have a Windows environment.

**Comment by AbhaMoitra** [comment]
Thanks for update. Dan Russel was using a VM to run and update SADL models for RACK, and I believe he did not see the errors.
