### ISSUE TITLE
Graphing issue

### ISSUE THREAD

**Issue by AbhaMoitra** [SemanticApplicationDesignLanguage/sadl#568]
I have updated SADL with release corresponding to #565 and observed some warnings / errors. Specifically, for RACK Release 3.0, I see the following error
![image](https://user-images.githubusercontent.com/28540315/99275129-21107a00-27f9-11eb-8175-16604d279535.png)

**Comment by crapo** [comment]
@AbhaMoitra , I have no visibility into what "release correspoinding to #565" means. Did someone build you an internal release? On what branch? And "RACK Release 3.0" corresponds to what in the RACK Ontology repo?

**Comment by agabaldon** [comment]
@crapo, yes, it is an update built on development branch after the fixes for issue #565 were merged in.

**Comment by crapo** [comment]
@AbhaMoitra , this has been reproduced and resolved with PR #569. Awaiting review by @agabaldon .

**Comment by crapo** [comment]
@AbhaMoitra , can you please confirm that this fixed the problem and if so close this issue?

**Comment by crapo** [comment]
@AbhaMoitra has confirmed that this error is fixed.
