### ISSUE TITLE
Import of http://com.ge.research.sadl/sadlserver/Services in ServicesConfig.sadl shows error

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#572]
Created a ServicesConfig.sadl file which resulted in the generation of a SadlServicesConfigurationConcepts.owl file in OwlModels. Then adding
 import "http://com.ge.research.sadl/sadlserver/Services".
to ServicesConfig.sadl shows error
  Couldn't resolve reference to SadlModel 'http://com.ge.research.sadl/sadlserver/Services'.

**Comment by crapo** [comment]
Just realized this is duplicate of #550. It is also related to #549 .

**Comment by crapo** [comment]
@agabaldon , I think that this issue can be closed with the merging of PR #573 . Do you agree?

**Comment by agabaldon** [comment]
This and #549 ?

**Comment by crapo** [comment]
yes, I believe so

**Comment by crapo** [comment]
With all outstanding PRs merged, I believe this is resolved.
