### ISSUE TITLE
Meaning of "a single value of type Seat"

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#576]
@AbhaMoitra , in looking at #509 , I realized that this expression in SADL:

`Bicycle is a class,
	described by component with values of type Wheel,
	described by component with a single value of type Seat.`

is creating a cardinality restriction on component:

`  <owl:Class rdf:ID="Bicycle">
    <rdfs:subClassOf>
      <owl:Restriction>
        <owl:cardinality rdf:datatype="http://www.w3.org/2001/XMLSchema#int"
        >1</owl:cardinality>
        <owl:onProperty>
          <owl:ObjectProperty rdf:about="#component"/>
        </owl:onProperty>
      </owl:Restriction>
    </rdfs:subClassOf>
  </owl:Class>`

This makes no sense as that would mean that if a Bicycle has a Seat it can have no Wheels and vice versa.

So I believe we need to, for object properties at least, translate the SADL above to a qualified cardinality restriction.

`    <rdfs:subClassOf>
      <owl:Restriction>
        <owl:onClass rdf:resource="#Seat"/>
        <owl:qualifiedCardinality rdf:datatype="http://www.w3.org/2001/XMLSchema#long"
        >1</owl:qualifiedCardinality>
        <owl:onProperty>
          <owl:ObjectProperty rdf:ID="component"/>
        </owl:onProperty>
      </owl:Restriction>
    </rdfs:subClassOf>
`

Since this is potentially impactful to anyone using SADL, I want to have complete consensus before making a change. @agabaldon , @weisenje , please review.

**Comment by AbhaMoitra** [comment]
I agree that cardinality restriction makes no sense and needs to be altered.

**Comment by crapo** [comment]
This will be closed when PR #578 is merged.

**Comment by tuxji** [comment]
Closing now that #578 is merged.
