### ISSUE TITLE
"or" in body of rules translates as "and"?

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#582]
From the old SADL documentation, it seems "or" is not allowed in the body of rules. I wrote a simple rule to check anyway:
AC is a class described by acprop with values of type boolean.
BC is a type of AC.
Rule testr: if x is a AC or x is a BC then x acprop true.

Turns out:
1) SADL does not complain about the "or"
2) The "or" is translated as "and":

[testr: (?x rdf:type http://sadl.org/test.sadl#AC), (?x rdf:type http://sadl.org/test.sadl#BC) -> (?x http://sadl.org/test.sadl#acprop 'true'^^http://www.w3.org/2001/XMLSchema#boolean)]

**Comment by crapo** [comment]
@agabaldon , disjunction in rules is not invalid in SADL. It is supported by the SWI-Prolog reasoner. The error should come from the JenaTranslatorPlugin, as Jena rules do not support "or". I've thought about allowing "or" in rules and translating to multiple rules, one for each element of the disjunction. That would lead to complexity for the user as there would not be a single rule to debug. I'll look into why you're not seeing an error. I thought there was one.

**Comment by crapo** [comment]
I see the regression error. Will resolve and improve error handling.

**Comment by crapo** [comment]
Immediate error on or to and is fixed. Messaging is reworked so that translator can do validation during onValidate and errors go to markers in editor. Substantial rework of how junctions are handled in IntermediateForm to allow differentiation of disjunction and conjunction.

**Comment by crapo** [comment]
When PR #593 is merged this issue should be closed.
