### ISSUE TITLE
Sub-property syntax question

### ISSUE THREAD

**Issue by AbhaMoitra** [SemanticApplicationDesignLanguage/sadl#594]
@crapo : Is the following allowed? 

![image](https://user-images.githubusercontent.com/28540315/103244230-577a0280-492a-11eb-8921-53a9bebfe139.png)

I ran into this when converting https://github.com/yzhao30/PATO-ROSE/blob/master/ontology/c.owl to a SADL file. In this conversion, there were just a few errors and I am trying to understand them.

**Comment by crapo** [comment]
@AbhaMoitra , these constructs generate no errors and the OWL translation looks to me to be correct. In that sense I think they are "allowed". Presumably this is not one of the "few errors" you encountered....

**Comment by AbhaMoitra** [comment]
@crapo -it is the root cause of the error I see in c.sadl. In a small snippet, when I use subprop1, it is not viewed as a property. So I have

![image](https://user-images.githubusercontent.com/28540315/103301051-7631d500-49ce-11eb-8db9-5398335cdca9.png)

And the error says 
             'subprop1' is not a property

**Comment by crapo** [comment]
@AbhaMoitra , I encourage you to use Discussions rather than Issues for non-issues, which this seems to me to be. When you are satisfied with the dialog please close this issue.

**Comment by crapo** [comment]
This is a slightly different construct than in your first post. I do see the error now. Will look into it. I failed to notice the coloring of subprop1 in your first post.

**Comment by AbhaMoitra** [comment]
@crapo : I will use Discussion in the future. Thanks.

**Comment by crapo** [comment]
@AbhaMoitra , I misunderstood. Because I didn't notice the color error (subprop1 colored as class, not property) I thought this was just a question, not the reporting of an issue. This is where it belongs as it is an issue.

**Comment by crapo** [comment]
@AbhaMoitra , I think you will get notification that PR #595 fixes this issue. @tuxji , where is the zip that is automatically created that Abha could use if she wanted this fix immediately? If I understood, there is an update zip automatically created when ?tests pass? on merge to development?

**Comment by tuxji** [comment]
@crapo Yes, SADL's GitHub Actions workflow has automatically created an update zip twice: 1) while checking that the pull request builds successfully (SADL Continuous Integration Workflow [#18](https://github.com/SemanticApplicationDesignLanguage/sadl/actions/runs/452703104)), and 2) after merging the pull request into the main branch (SADL Continuous Integration Workflow [#19](https://github.com/SemanticApplicationDesignLanguage/sadl/actions/runs/453190044)).  Either you or Abha can find the latest update zip anytime by drilling into the [Actions](https://github.com/SemanticApplicationDesignLanguage/sadl/actions) tab and clicking on the most recent successfully completed run in the list of workflow results.

**Comment by crapo** [comment]
Thanks @tuxji ! I've add instructions on installing the latest bleeding edge as a note in the installation instructions.
