### ISSUE TITLE
No warning when a property has another property as domain

### ISSUE THREAD

**Issue by AbhaMoitra** [SemanticApplicationDesignLanguage/sadl#597]
In the following snippet, there is no error / warning for the last line.

![image](https://user-images.githubusercontent.com/28540315/103660797-05456c80-4f3c-11eb-9ab6-c9d1e1e9d0c7.png)

I think the user had wanted to say the following:

![image](https://user-images.githubusercontent.com/28540315/103661040-46d61780-4f3c-11eb-951f-346f076c0b93.png)

I think SADL should show a error / warning, but it does not.

**Comment by crapo** [comment]
This can be closed when PR #598 is merged.
