### ISSUE TITLE
Duplicate instances in sadl file from OWL import

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#614]
When importing this owl:

<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:builtinfunctions="http://sadl.org/builtinfunctions#"
    xmlns:owl="http://www.w3.org/2002/07/owl#"
    xmlns:sadlimplicitmodel="http://sadl.org/sadlimplicitmodel#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:owlimp="http://sadl.org/testOwlimport.sadl#"
    xmlns:sadlbasemodel="http://sadl.org/sadlbasemodel#"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
  xml:base="http://sadl.org/testOwlimport.sadl">
  <owl:Ontology rdf:about="">
    <owl:imports rdf:resource="builtinfunctions"/>
    <owl:imports rdf:resource="sadlimplicitmodel"/>
    <owl:imports rdf:resource="sadlbasemodel"/>
  </owl:Ontology>
  <owl:Class rdf:ID="C"/>
  <owl:DatatypeProperty rdf:ID="description">
    <rdfs:domain rdf:resource="#C"/>
    <rdfs:range rdf:resource="http://www.w3.org/2001/XMLSchema#string"/>
  </owl:DatatypeProperty>
  <owlimp:C rdf:about="aninstance">
    <owlimp:description>sample instance</owlimp:description>
  </owlimp:C>
</rdf:RDF>

The resulting SADL file contains:

--------------------------------------------------
uri "http://sadl.org/testOwlimport.sadl" alias owlimp
    (note "This ontology was created from a SADL file 'testOwlimport.sadl' and should not be directly edited.").

// Class definitions:
C is a class,
    described by description with values of type string.

// Individuals:
aninstance is a C,
    has description "sample instance".

// Other statements:
http://sadl.org/aninstance is a C.

--------------------------------------------------

The last statement is redundant and also shows an error.
The source of the problem seems to be the use of rdf:about instead of rdf:ID.

**Comment by crapo** [comment]
@agabaldon , I assume on the 3rd to the last line you meant

<owlimp:description>sample instance</owlimp:description>

Otherwise it doesn't not parse. With that modification I get the translation you show.

**Comment by crapo** [comment]
@agabaldon , also the rdfs:comment on the ontology shown in the SADL output ("(note "This ontology was created from a SADL file 'testOwlimport.sadl' and should not be directly edited.")") is not shown in the OWL model. I assume that you have removed it from the OWL?

**Comment by agabaldon** [comment]
The html viewer was interfering with the rdf. Here it is as quoted code:

```
<rdf:RDF
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:builtinfunctions="http://sadl.org/builtinfunctions#"
    xmlns:owl="http://www.w3.org/2002/07/owl#"
    xmlns:sadlimplicitmodel="http://sadl.org/sadlimplicitmodel#"
    xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
    xmlns:owlimp="http://sadl.org/testOwlimport.sadl#"
    xmlns:sadlbasemodel="http://sadl.org/sadlbasemodel#"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
  xml:base="http://sadl.org/testOwlimport.sadl">
  <owl:Ontology rdf:about="">
    <owl:imports rdf:resource="builtinfunctions"/>
    <owl:imports rdf:resource="sadlimplicitmodel"/>
    <owl:imports rdf:resource="sadlbasemodel"/>
  </owl:Ontology>
  <owl:Class rdf:ID="C"/>
  <owl:DatatypeProperty rdf:ID="description">
    <rdfs:domain rdf:resource="#C"/>
    <rdfs:range rdf:resource="http://www.w3.org/2001/XMLSchema#string"/>
  </owl:DatatypeProperty>
  <owlimp:C rdf:about="aninstance">
    <owlimp:description>sample instance</owlimp:description>
  </owlimp:C>
</rdf:RDF>
```

**Comment by crapo** [comment]
@agabaldon , another issue with the OWL model I believe is that if you use "rdf:about", as is done for the instance declaration, and it is a relative URI, it should be "#aninstance". See https://www.w3.org/TR/rdf-syntax-grammar/#section-Syntax-ID-xml-base. The output to Other Statements is a bug, which is fixed in the forthcoming PR, but the output of the entire URI in that statement is on purpose to bring attention to the error.

**Comment by agabaldon** [comment]
@crapo: thanks for the fix! 
The triple that uses rdf:about="aninstance" is Jena generated through the addDataProperty method. Looks like non-compliance?

**Comment by crapo** [comment]
What were the arguments in the call to addDataProperty?

**Comment by agabaldon** [comment]
They were objects of type Jena Individual, Property, and Literal.

**Comment by crapo** [comment]
@agabaldon , what I'm really trying to ask you is what was the URI of "aninstance" that was used to create it. I'm suspecting a bogus URI at that point in the process.

**Comment by crapo** [comment]
@agabaldon , I don't  see that we have resolved where the invalid URI came from in the first place. Do you want to pursue this? If not please close this issue.

**Comment by agabaldon** [comment]
The URI was also Jena generated. But I have lost track of the files so I'll close the issue.
