### ISSUE TITLE
Data cardinality constraints show an error.

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#617]
Object cardinality constraints work fine, but data cardinality constraints are showing an error:

![Screen Shot 2021-02-05 at 3 19 02 PM](https://user-images.githubusercontent.com/4990550/107084791-81460500-67c5-11eb-8701-f380a352c758.png)

**Comment by crapo** [comment]
This is fixed with PR #618 . Good catch!
