### ISSUE TITLE
CSV to SADL relationShip mapping is not happening

### ISSUE THREAD

**Issue by NAVEENKUMARSKPN** [SemanticApplicationDesignLanguage/sadl#627]
I have installed latest version of SADL and i was trying to import csv which has two classes and relationship for each class

Person,rel,role
A,has_Role,admin
B,has_Access,DB

the above csv is a sample and while importing it should be like "Relationship of A to role is has_Role ."

for this how will i need to generate a tmpl file ... as I am able to import classes as well instances from csv to sadl but cant able to map relation from csv to sadl..

please help me on this 
Thanks

**Comment by crapo** [comment]
@NAVEENKUMARSKPN , for starters, curious to know if you looked at this documentation linked to the topical index: http://semanticapplicationdesignlanguage.github.io/sadl/CsvDataImporter.html. 

The purpose of the CSV Importer is to import instance data to a pre-existing meta-model. It kind of seems that you are trying to create that meta-model from scratch using the CSV file? Usually the properties and classes are defined in the meta-model. In your example, I assume that "A" and "B" are instances of the class "Person". The 3rd column is labeled "role", so assuming that this is also a class, and making it camel-case per convention, the meta-model might be:

` uri "http://sadl.org/Meta.sadl" alias meta.

 Person is a class.

 Role is a class.

 has_Role describes Person with values of type Role.

 has_Access describes Person with values of type Role.
`
Then the template, which imports the meta-model, might contain the triples :

`uri "http://sadl.org/data/gh627" alias gh627data.

import "http://sadl.org/Meta.sadl".

<A> is a Person.

<C> is a Role.

<A> <B> <C>.`

The result of the import, in SADL syntax, would then be:

`uri "http://sadl.org/data/gh627" alias gh627data
    (note "This ontology was created from a CSV data source.").

import "http://sadl.org/Meta.sadl" as meta.

// Individuals:
^A is a meta:Person,
    has meta:has_Role admin.
B is a meta:Person,
    has meta:has_Access DB.
DB is a meta:Role.
admin is a meta:Role.`

**Comment by NAVEENKUMARSKPN** [comment]
Thanks crapo
