### ISSUE TITLE
Type SADL error with a list

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#628]
The following model causes SADL to issue an error which I think should not be even a warning.

 uri "http://sadl.org/list.sadl" .
 
 B is a class.
 C is a class.
 D is a class described by p with values of type B List .
 
i1 is a B.
i1 is a C.
 
i2 is a D has p [i1].

**Comment by agabaldon** [comment]
If I change 
  i1 is a B.
  i1 is a C.
to
  i1 is a {B and C}.

in addition to the error I also get a warning.

**Comment by crapo** [comment]
@agabaldon, this issue uncovers a gap in implementation. Type checking of union and intersection classes  doesn't appear to be implemented--there are some "TODO"s in the code in this area. It will probably take some time and effort to correctly fill these gaps.
In the meantime, if this is something that you need to have working, you might try naming the intersection class.

`BC is the same as {B and C}.
i1 is a BC.`

Please keep me informed of any additional issues that you encounter in this area. I'll let you know when I think this is resolved.

**Comment by agabaldon** [comment]
Thanks @crapo. This is not blocking me for now, so not urgent.
I did find another example that gives unexpected results. 

This SADL model:

uri "http://sadl.org/list.sadl" .
 
 B is a class.
 C is a class.
 D is a class described by p with values of type BC List .
 
BC is the same as {B or C}.
 
i1 is a B.
i2 is a C.

 
i3 is a D has p [i1,i2]. 

gives a warning that the list elements are not of the same type. No errors. But the resulting OWL has this for i2:

`<sadllistmodel:first>
          <B rdf:ID="i2">
            <rdf:type rdf:resource="#C"/>
          </B>
        </sadllistmodel:first>`

seems to say that i2 is both a B and a C. 

Also not urgent to fix, but I wanted to document so we can keep track.

**Comment by crapo** [comment]
Closing as PR #631 has been merged into development.
