### ISSUE TITLE
translation of "is not a"

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#633]
I wrote a simple ontology with three classes:

  B is a class.
  C is a class.
  D is a class.

I tried to write that i1 is a B but not a C:

  i1 is a B.
  i1 is not a C.

But I get an error at the "i1 is not a C" line: 
"Multiple markers at this line
- Unexpect empty array in processSadlDifferentFrom
- mismatched input 'C' expecting 'same'

I also wanted to write the rule:
  Rule r:
   if x is a B and x is not a C
   then  x is a D.

and noticed that it gets translated into:

[r: (?x rdf:type http://sadl.org/neg_rule_test.sadl#B), noValue(?x, rdf:type, ?v0) -> (?x rdf:type http://sadl.org/neg_rule_test.sadl#D)]

which doesn't look right. 

Is this something that needs further work or a bug?

**Comment by agabaldon** [comment]
I just noticed that the query:
  Ask: select x where x is not a C.
is translated into:
Query: select ?x where {?x <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://sadl.org/neg_rule_test.sadl#C>}

**Comment by crapo** [comment]
@agabaldon , the SADL grammar is bifurcated into statements that define classes, instances, and properties on the one hand and expressions that can be used in rules, queries, tests, etc. on the other. They are not entirely unified, but it was the best that could apparently be done in designing the SADL 3 grammar with some level of backwards compatibility. Plus, it's not entirely clear that one should be able to define new classes in expressions.

WRT your specific example, "not a C" is defining a class which is the compliment of C. Generally speaking, the compliment of a class is defined within another class, the universe. This is covered in the Foundational Concepts tutorial, see http://semanticapplicationdesignlanguage.github.io/sadl/Tutorial/FCSM_BasicSetTheory.pdf slide 5.

What you can say legally in SADL is this:
NotC is the same as not C.   // definition of compliment of C
i1 is a {B and NotC}.

Without a universe defined (other than owl:Thing), and unless B and C overlap (have an intersection), "and NotC"  is a meaningless addition as NotC is a very large class that includes B.

With the valid definitions above, the rule can be written as:
Rule r: if x is a B and x is a NotC then x is a D.

This gets a warning which is erroneous that I thought was fixed but apparently not. I'll take a look at that.

WRT the SADL query "Ask: select x where x is not a C.", the translation is clearly incorrect. What would you expect it to translate to in SPARQL? One possibility is this:

select ?x where { ?x <rdf:type> ?t . filter(?t != <C>)}

This query returns a lot of stuff, everything that is a class or instance in not just this model but the SadlBuiltinFunctions and SadlImplicitModel models, including a lot of bnode restrictions. Better suggestions for the translation?

**Comment by crapo** [comment]
The erroneous type checking error is resolved with a commit to branch #628, which is added to PR #631.

**Comment by crapo** [comment]
@agabaldon , hoping you'll tell me what you think "Ask: select x where x is not a C." should translate to in SPARQL....

**Comment by agabaldon** [comment]
I think it should be translated into 

  select ?x where { filter not exists{?x rdf:type ns:C} }

that will give an error but I think that's ok. "Ask: select x where x is a B and x is not a C" will work.

**Comment by crapo** [comment]
@agabaldon , not sure what you mean by "that will give an error but I think that's ok." Here is my simple test case:

 B is a class.
 C is a class.
 
 i1 is a B.
 i2 is a C.

If I execute this SPARQL query, which I think is the expansion of what you are suggesting as the translation
`select ?x where {filter not exists{?x <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://sadl.org/gh633b.sadl#C>}}`

 against the model I get no results. Seems to me that the proposed translation is not satisfactory. What am I missing?

**Comment by agabaldon** [comment]
I wasn't sure if it returned an error or just not work as expected. But the query:

`Ask: "select ?x where {?x a <B>. filter not exists {?x a <C>}}".`

does work as expected.

**Comment by crapo** [comment]
This query against the model above with two classes and two instances, and given that it imports implicitly the SadlImplicitModel and the SadlBuiltinFunctions model, returns the following. Not sure what filters, if any, should be automatically included in the translation...
     "x"
     "i1"
     "C"
     "B"
     "http://sadl.org/gh633b.sadl"
     "http://sadl.org/sadlbasemodel"
     "06a21e1a-9875-40ce-8aa7-bc1b2eaa5314(blank node)"
     "2b739f75-54fb-47c5-98b9-2bac3560f7c6(blank node)"
     "0b9b3c02-635b-4546-9ed8-366950818911(blank node)"
     "faa452df-bc1f-4179-9968-ef2ec37a3666(blank node)"
     "3749fb79-cddf-45cb-a565-7f24aaafb756(blank node)"
     "Python"
     "6fc3ed75-64c6-4dc7-92f5-bffda931f9e0(blank node)"
     "gpObject"
     "derivedFrom"
     "9db6be63-c9e2-4c92-9d8b-99268c65a673(blank node)"
     "stddev"
     "dataType"
     "DataTable"
     "FunctionPattern"
     "Plus"
     "anyDataType"
     "02122e1c-1293-4021-9d2a-f23524ef8e51(blank node)"
     "18b34871-8859-4bc8-a8cb-483bcec4f686(blank node)"
     "semType"
     "DataDescriptor"
     "GPVariable"
     "f949af28-e05b-49af-a265-a9f5d4fb2745(blank node)"
     "9ca6546f-85dd-42d7-bedd-4825f6dbd7b5(blank node)"
     "c1e44a92-73e3-47a0-81bc-1b7e7947070b(blank node)"
     "70a0a3c7-c428-4b0b-bfc4-977faa903784(blank node)"
     "arguments"
     "AugmentedType"
     "ExternalEquation"
     "08789393-2f2e-48d8-acd9-51629be70f7a(blank node)"
     "7fd6bbdd-773b-4476-8665-783640f5d847(blank node)"
     "GPLiteralValue"
     "bd02791b-1466-4d08-9190-d16a61759f9c(blank node)"
     "3df2d52e-882b-4781-a90f-91c4bf8a35ea(blank node)"
     "0c51e95c-8929-4d2a-9d86-7b5e2e67ffcd(blank node)"
     "rowValues"
     "92876b03-a33f-4e46-a7ff-8e229d57dc58(blank node)"
     "059b6c5d-5579-4159-817c-05fb94779128(blank node)"
     "dataContent"
     "augTypeUnits"
     "OtherLanguage"
     "2cb9b7f6-bab1-4a70-a648-4c5bc7f2af12(blank node)"
     "ThisArgument"
     "8535751b-09f0-481d-a2d8-d02be9a7486d(blank node)"
     "SemanticConstraint"
     "expression"
     "Script"
     "argValues"
     "externalURI"
     "3fb7e9cf-a0d4-4c8a-a499-e7632fbcbbc1(blank node)"
     "d3993c5b-f71f-45bd-987f-6a34ff7fcbed(blank node)"
     "2b5c5371-4d0b-4c60-8896-0366fb5efead(blank node)"
     "b2fb79d7-a0e3-4bfa-ae11-eac9113bbac5(blank node)"
     "af4730e2-8c8b-407c-8074-33d3f9c6184e(blank node)"
     "localDescriptorName"
     "http://sadl.org/sadlimplicitmodel"
     "gpLiteralValue"
     "7fbac340-51e3-413f-903c-9e4dd8247956(blank node)"
     "UnittedQuantity"
     "f9f625dd-0057-4607-84a3-5817120a1b84(blank node)"
     "gpVariableName"
     "Java"
     "language"
     "ScientificConcept"
     "Rule"
     "unit"
     "NamedQuery"
     "gpSubject"
     "656e347f-60a4-4b8c-ae42-43db577f974e(blank node)"
     "impliedProperty"
     "GPResource"
     "returnTypes"
     "c977f09b-dc78-495f-b536-438ad529f681(blank node)"
     "script"
     "GPAtom"
     "gpPredicate"
     "66775d67-4607-4734-9c3a-19d54197d74e(blank node)"
     "TriplePattern"
     "SemanticType"
     "builtin"
     "GraphPattern"
     "bf7bc87b-1f56-4aca-a459-a97b17544980(blank node)"
     "254efdca-7235-403e-854b-9e5539247b30(blank node)"
     "Language"
     "descriptorVariable"
     "specifiedUnits"
     "externalURL"
     "DataTableRow"
     "dataLocation"
     "c1b2c773-b077-4c0d-803a-aad9453afe46(blank node)"
     "cfc6c4bc-bab8-46d2-b1ca-9873ecb6966d(blank node)"
     "8e664907-7f7a-4b89-9e7c-50ea8d0424ba(blank node)"
     "constraints"
     "expandedProperty"
     "augmentedType"
     "Text"
     "61deb2f3-0ea3-40e2-b345-9e6045d1ce38(blank node)"
     "Equation"
     "value"
     "columnDescriptors"
     "d0e538f1-bae1-4124-9eea-475ded835cda(blank node)"
     "listtype"
     "maxLengthRestriction"
     "minLengthRestriction"
     "lengthRestriction"
     "rest"
     "http://sadl.org/sadllistmodel"
     "List"
     "first"
     "10a6a944-fd07-4359-af95-1b75bf9c4502(blank node)"
     "a70d12f8-3602-4639-82c0-499de66ffb84(blank node)"
     "7fc44fe6-de06-4b77-9244-87cf2f679143(blank node)"
     "fd52c411-75c9-43fd-8683-62e1974740ad(blank node)"
     "61fa5e6f-b70e-4647-892c-24de9bc4c873(blank node)"
     "listNotContains_X"
     "93f016d9-f5dc-43f6-a01e-feebf9831d21(blank node)"
     "907b2418-9528-4cf0-928b-c04749fef199(blank node)"
     "8e10c9ac-5245-426f-87d8-324795496829(blank node)"
     "4c3bee79-d08c-4bfc-a783-7e782ce73fb3(blank node)"
     "1f6665d7-13e3-4cb0-b793-bf0cc530391f(blank node)"
     "614dc75e-abf7-49da-bdaf-1bd790484db9(blank node)"
     "121107d2-2678-4c38-94bf-38d56ca91d22(blank node)"
     "acos_X"
     "12817e66-4bbb-4d0f-be37-4e1e63100b6b(blank node)"
     "56e724ca-d83f-4719-99f6-27cbcbb9fc89(blank node)"
     "13d25240-dfe7-4a30-ac71-fed9473348ea(blank node)"
     "unbound"
     "isDType_X"
     "d5f6d7de-3165-4fc2-aea5-b271d8378c6a(blank node)"
     "11c12f39-f15e-4a62-949a-cb1913713b87(blank node)"
     "sin"
     "16a49f0f-c0da-4402-99fd-465989b50794(blank node)"
     "8a429386-709c-4d0c-85b6-07997c7d86a7(blank node)"
     "a04bcd7a-b36a-4d5d-8711-41f9868b61ff(blank node)"
     "819a4d3b-e04c-4224-9c64-1b102147672b(blank node)"
     "5356f1f0-5b54-494b-ab44-eef2af36d27b(blank node)"
     "134412a3-78b3-48c9-8678-90b5a2fcbd16(blank node)"
     "8b0557c0-ddff-4e25-878e-8dce168de85b(blank node)"
     "d744a9df-dca2-44cc-bb46-4b3c4cad6013(blank node)"
     "pow"
     "f61b790c-2708-41d7-9ff6-7112df85c73b(blank node)"
     "b0f8ea2c-a336-4eaf-a5f2-01e49d1705fb(blank node)"
     "9a325864-6f83-4be3-a852-450dbc392827(blank node)"
     "bound"
     "09964833-405e-4d1f-8dd0-4499debaa39b(blank node)"
     "e71bb89e-2000-4941-acf9-9ff3ac591fe6(blank node)"
     "dc63a9cb-3b2f-4e15-8901-52de3c7aa995(blank node)"
     "dd480483-1c9e-42a5-8ce5-fc1221e1e183(blank node)"
     "70d37b6c-40cd-4d56-90a6-b1fc35b8ecac(blank node)"
     "d771ecc5-78b8-415c-9fae-b97be952d55f(blank node)"
     "countMatches"
     "6bc80d59-f495-4ce4-81e0-0e56b01e5a8d(blank node)"
     "http://sadl.org/builtinfunctions"
     "7f0268b7-d010-4bd3-8fef-a101abf3d8c0(blank node)"
     "tan"
     "getClassFromConstraint"
     "d0bc0d3f-509c-4b3a-8211-89f8d19cade2(blank node)"
     "listNotEqual"
     "bbd686c4-f60f-4760-9e3e-e48ba5e8a665(blank node)"
     "e59b3b43-5da4-49c5-bb4f-11a62621cbbb(blank node)"
     "1b4daea9-9930-492d-9e78-5c16b22a7b51(blank node)"
     "b26709a1-e105-45c9-a7a3-7bb8d379c87f(blank node)"
     "0ab49438-4cd3-40dd-ab82-f5c7a20f6e32(blank node)"
     "2ec31611-5ee6-4396-bc6a-960ee3161c2b(blank node)"
     "le"
     "f13660ee-14de-4605-9453-21668ef0b286(blank node)"
     "ccef431e-465e-474d-8419-95fdf52c05ea(blank node)"
     "e9fa151c-fc28-48ea-8ea1-0013e61dd3f8(blank node)"
     "5408fa99-ad16-43b3-a27e-8aecac04f678(blank node)"
     "aa706653-da75-419d-95c1-cfeea2cb44ca(blank node)"
     "2de872d6-b06b-4891-84b3-94adf6d67737(blank node)"
     "f2d07ce0-f971-406b-8089-1915ee1e2325(blank node)"
     "80ca9687-d608-4a86-b4df-7e74859c5f6f(blank node)"
     "ge_X"
     "3dc4b251-fafb-4426-a4ad-bd5528202c67(blank node)"
     "ff2956c6-6662-4d5d-9b4c-98b2b01556f9(blank node)"
     "e6aa8c98-1c37-4879-b929-551e9e8e06af(blank node)"
     "notBNode_X"
     "noSubjectsOtherThan"
     "51b64e7f-e311-42c3-8238-32c541c27838(blank node)"
     "8ddcd778-2804-4c61-94e1-2aa0c56385ff(blank node)"
     "9c901ab1-9354-4c0a-a443-7bcd4c8687f1(blank node)"
     "listConcat"
     "uriConcat_X"
     "cos"
     "055079bd-bebc-4100-b216-ae9bd876ed49(blank node)"
     "519df63f-d583-459b-a2a8-044898d75ca2(blank node)"
     "d6660975-68b9-4345-be54-cf7e6a71bb8c(blank node)"
     "product"
     "41671368-6ea1-4136-a51b-fd192b8d2d6f(blank node)"
     "d6b8e5d7-f56a-425a-95bf-808cc5a7be50(blank node)"
     "88fc8704-41f5-4bdc-8842-a0ee4e2bcf25(blank node)"
     "8c36e633-b05b-4bef-90d5-fd21f605aa89(blank node)"
     "d0b9ffb4-1129-46eb-a104-8e1d5a77d61e(blank node)"
     "cf30dee4-868e-4f96-95ec-93f44e1dd622(blank node)"
     "b985d99b-63c1-4853-a573-5233bccfc383(blank node)"
     "9d8d6f43-5638-4b2f-a5c9-d51471475936(blank node)"
     "c1869903-342c-40b2-86df-131d6b2ec000(blank node)"
     "091dd285-db0d-4b40-a628-605dd60857e4(blank node)"
     "a03a84a7-5c44-4abd-9b63-9195a6102098(blank node)"
     "difference"
     "c5978a77-bb79-4617-b5eb-79c2ed9f6637(blank node)"
     "729a893c-7c98-474f-bd38-0150b99164b4(blank node)"
     "noUnknownValues"
     "unique"
     "1de58799-d047-4487-ab80-a9adb279be3f(blank node)"
     "ca3f450e-4a9a-49fe-9975-c87670272fcf(blank node)"
     "46257b97-93c8-4f7e-b238-aee6d1b5fe76(blank node)"
     "listMapAsObject"
     "0a2f14c4-b288-4e1a-a111-db139596cdee(blank node)"
     "listToString"
     "f987d63c-f922-4fed-b60b-d607ce158ffd(blank node)"
     "noValue"
     "bound_X"
     "isLiteral_X"
     "notBNode"
     "e55ce3d0-acdf-430e-8f60-03f8d129bdb8(blank node)"
     "359c48bd-527a-46f5-9dfb-59d729ff31b8(blank node)"
     "d72dbad6-ff44-4bbe-a89e-a4891b9c25fb(blank node)"
     "85af7658-f603-4c57-b864-c5832bab2ab8(blank node)"
     "770cf1d1-48f5-439a-b547-f71a67c6079b(blank node)"
     "3a33773b-5a2e-44ee-bd81-92bbcadc930e(blank node)"
     "notBType"
     "b3204971-da98-4321-96b8-7a4cf8f952f8(blank node)"
     "notLiteral"
     "5af0e8af-3037-4a40-b8a7-99161a2ba3c7(blank node)"
     "f0ef1e47-a389-4f6e-9db4-85b39ec0c13d(blank node)"
     "86335bf7-1ed9-43aa-ab1c-f1857cf85768(blank node)"
     "78d73e37-2441-412d-84b9-c81f1a40c98a(blank node)"
     "34d8f1c9-d646-46f9-90c1-a206aa4a9b9c(blank node)"
     "4a3ddb40-5d37-48dc-8a61-c8a38ba5e95f(blank node)"
     "notLiteral_X"
     "difference_X"
     "9ff623da-5908-43f3-a7e3-8ea872a04bf0(blank node)"
     "c4e48abe-bba0-4699-8f25-d6a10be8e582(blank node)"
     "listEntry_X"
     "c5ffcedc-fce2-4e38-9275-be3b5cc05fc6(blank node)"
     "assign"
     "64fbf41b-bf38-48f6-8c98-8c02b0995d97(blank node)"
     "floor"
     "bf2661d2-ecba-4b7c-b506-e63b456050f7(blank node)"
     "a3e1bb0d-63bb-4778-ab1c-4c4cf4a9c414(blank node)"
     "47039c03-0e4c-4e94-bbee-791f3fb0cfb4(blank node)"
     "0bdc35dc-c631-4ff8-868f-fd56adcddacd(blank node)"
     "strConcat_X"
     "subtractDates"
     "isDType"
     "list"
     "tableAll"
     "4a88fa25-21ee-41a5-8940-235bcf06abdd(blank node)"
     "f8f24765-057f-4cc6-afc3-4ba5b0834b1a(blank node)"
     "b5c10dde-1556-443c-b415-73463651e312(blank node)"
     "listLength_X"
     "acos"
     "16e94ca4-843d-4ac4-819a-fc49dde44e2b(blank node)"
     "207218ee-8e29-4fe2-b1ab-143f35650883(blank node)"
     "54d82daf-9b07-4d33-8e6a-01f48772d914(blank node)"
     "234d1ae3-ac04-4ba9-b8f7-dab9bfcec8f3(blank node)"
     "sum"
     "382ff9d8-e6f1-47bd-a560-39afc3235802(blank node)"
     "c81ac4aa-26a6-4138-8808-8e1f3d61dc1d(blank node)"
     "4674c842-af65-4cae-9acb-5ab122da95b2(blank node)"
     "a12e37e9-cf91-4201-a860-0d4fd7da6ba5(blank node)"
     "1f7cf15e-913d-44b8-a42e-0780c92758ad(blank node)"
     "3b1a39e1-2f50-4361-aa72-db84d2cb35af(blank node)"
     "b111f4a7-d893-43f3-8dfa-21da0085ae98(blank node)"
     "252ba736-f103-40e3-ad9e-67cae1260243(blank node)"
     "fefc4418-46c6-4029-b45b-6a3b31645286(blank node)"
     "3b6cb76d-d2aa-4f0e-9bd9-f8b388920ed0(blank node)"
     "regex"
     "countLiteralValues"
     "3e407643-9484-4830-bf3d-6cc6818236d7(blank node)"
     "771eaf61-0a19-4c82-868e-fbf9010be5fa(blank node)"
     "atan"
     "notBType_X"
     "4dba2e43-6847-495d-9e41-75d92ee54f2b(blank node)"
     "45574522-a595-4c07-9407-0ab655ea8583(blank node)"
     "sqrt_X"
     "notOnlyValue"
     "9a5ed3e5-3da4-4e1a-8904-71ed4371fe5f(blank node)"
     "c9480a08-56e5-40f3-b2dc-5dce2e4d0686(blank node)"
     "print"
     "fc3b0da4-31da-45de-975b-00657b5168ae(blank node)"
     "ceiling"
     "e4298522-2142-4bc9-afd0-6991031c2798(blank node)"
     "notDType"
     "addOne"
     "1aec0035-b343-468d-987f-50b13d6125a2(blank node)"
     "now"
     "556b184a-afa2-452d-bc6f-607455d6e7dc(blank node)"
     "e5b30142-297e-416c-8f3c-4f5360dfa669(blank node)"
     "afde88a3-eeea-4462-9c4d-589b1aa6cd20(blank node)"
     "c354b76c-d90a-42b1-bc0a-98c95c32d8d7(blank node)"
     "uriConcat"
     "min_X"
     "listNotEqual_X"
     "isBNode_X"
     "073f6e56-9245-4dd4-87c3-7df55b3eb768(blank node)"
     "oneOf"
     "2e005163-cc3c-4630-ad76-164178b91dab(blank node)"
     "5c1f8221-9fcc-4e4f-97bf-868b1a5e7895(blank node)"
     "569a10ec-9a47-46e5-88c7-3a5017f6a9f7(blank node)"
     "416e82fa-40e1-4478-ad24-393531092953(blank node)"
     "d59829ac-c248-417a-982f-f1f902134857(blank node)"
     "addOne_X"
     "listMapAsSubject"
     "e60b87bf-293d-44d3-9fad-2916f69d12cd(blank node)"
     "2d9af5ee-ca20-4439-8846-a32d36d54023(blank node)"
     "listSubtract"
     "min"
     "listLength"
     "unbound_X"
     "listEntry"
     "listEqual_X"
     "average"
     "79c7fb0f-041c-4e73-8ec6-8d518cc4c26b(blank node)"
     "7dc196e8-387b-4ecf-b309-14fdd79446e8(blank node)"
     "b843ce0c-2bc0-46ea-8d0e-90e60402f7a7(blank node)"
     "e3148ec1-9a82-4000-aea3-f82244aa2906(blank node)"
     "52e94293-5e87-47c6-b066-d358f91ad746(blank node)"
     "b807ffce-a049-43a8-a0be-a23aa4872c01(blank node)"
     "b21e8b8d-6c88-4cfe-bf48-3ee65b68fb54(blank node)"
     "5051c8d5-beef-4260-a203-244ee2eff9a7(blank node)"
     "dce4e2c4-2595-43c3-931f-68c24bb1781d(blank node)"
     "8ccb9826-c0c2-4ae6-8c64-0556cc360449(blank node)"
     "45f54f78-43c2-42fb-9fb8-ce0f4e4b8cc4(blank node)"
     "ebd6ff4a-764d-45ea-b895-358cb00fb57f(blank node)"
     "bd43a0e9-6cda-4bbf-8d4b-af162968e273(blank node)"
     "a2d84cc5-a86d-45de-9822-165a5d59e9e4(blank node)"
     "d9084bbc-d38c-42db-a71c-285b8fce7e48(blank node)"
     "27a62c33-63d3-4214-982a-961cc21199a8(blank node)"
     "388729ef-d897-40a5-96da-3bad0125c04e(blank node)"
     "listNotContains"
     "sqrt"
     "c738024e-9f09-4d71-a59b-f78b42b27ef1(blank node)"
     "ge"
     "0fa64994-deb2-4d6d-b36e-e03e5742ddc6(blank node)"
     "a9d9110d-d4f7-4a54-bff1-40c36f1a2ca3(blank node)"
     "eedd0bb8-23be-4d54-843e-097855947cef(blank node)"
     "greaterThan"
     "c4b19a28-b8a1-4191-bdea-633993fff627(blank node)"
     "listEqual"
     "0afbbd27-81de-4880-a62f-1d3435cdd105(blank node)"
     "a3138dbc-7d64-4199-a73e-664e7c67576f(blank node)"
     "c9f2b5ea-8bb7-49ae-ac94-92bad2f871c1(blank node)"
     "2baa1604-aa82-48ec-aa21-2a7c7cabd858(blank node)"
     "af7ee818-902c-4ab6-bf49-03868aa69ea6(blank node)"
     "9eb8e37e-dcfd-48d1-a205-e67b03d558d5(blank node)"
     "max_X"
     "isBNode"
     "notDType_X"
     "listContains"
     "countLiteralValues_X"
     "bcbfbac3-aa41-409e-8254-88d9162b3195(blank node)"
     "ffe2289b-5fa8-41fe-9d39-f723c1c097af(blank node)"
     "max"
     "fad1fea6-5533-485d-ac02-e62654dc3525(blank node)"
     "strConcat"
     "c2afbb09-3f87-439c-b44e-a1c57c786bae(blank node)"
     "f3a392cf-f529-4056-9e2e-081b64100cf4(blank node)"
     "fc9847fc-adaf-4b33-a291-e5f5fc10a40d(blank node)"
     "8e455e66-460f-4ad1-b42f-34ca8fb9f3bc(blank node)"
     "d698ace7-5d40-4119-9f90-4cec2d514b5c(blank node)"
     "1c4a42d5-632e-4d14-901b-914904fe6188(blank node)"
     "b409bf1d-acd1-4807-a1aa-be6fc56c6d2a(blank node)"
     "9afd54a5-fa92-413d-97ff-d02ef7ff594d(blank node)"
     "lessThan"
     "regex_X"
     "584d1fa4-27e5-4847-a364-86115d268ba0(blank node)"
     "f1b74df8-31e2-47e1-a55d-283d67ae80e2(blank node)"
     "27d38446-3906-4739-8080-a171b0863abe(blank node)"
     "6a82d8f3-970a-4a7a-834d-165cf7edfb1c(blank node)"
     "22951740-a8f3-4d90-bd64-ebcdca90f22f(blank node)"
     "2d5938c8-a54a-4104-8789-d72cd50db650(blank node)"
     "90012a20-68f8-49fa-b118-68b2c3059cec(blank node)"
     "c3bb4958-2fa9-44b4-8665-95f71708d69d(blank node)"
     "mod"
     "0cf8e69d-7e70-4a74-86ae-c90ac832e7d1(blank node)"
     "349c58d2-f44a-458f-84bf-035969198502(blank node)"
     "533b4b34-d414-454b-9a1e-75be1362b374(blank node)"
     "a1ac9157-397d-4c77-8f29-a9897b67174b(blank node)"
     "25684afd-b36b-45fd-b4c4-1014d1c2005f(blank node)"
     "b9789e06-ed54-47f6-bf5d-1c61a3fe0055(blank node)"
     "d0ffab9e-4826-4c8e-ac94-e7a5891f8f63(blank node)"
     "a6715484-0cd9-4b6a-a230-480a5bf19762(blank node)"
     "32d88ccc-79c0-48a9-9773-44c51fa18bca(blank node)"
     "7feda2c9-66c3-45c2-bd84-5f5edf761dc3(blank node)"
     "6b18b76c-ae50-48df-ba49-72e269e5bd7e(blank node)"
     "abs"
     "8877193c-8cb6-4219-9f39-c9eb50a22878(blank node)"
     "e2374227-f0f7-4a90-87d8-aa9e0789cc42(blank node)"
     "bdb74ee9-a341-492e-a661-05da39a8a66a(blank node)"
     "15cba21e-f3fe-4257-8d00-9a326f79e28a(blank node)"
     "62d77b0b-c8ef-4b02-99c8-7f1558ff171a(blank node)"
     "9e06c811-9c32-413a-805b-606f919b4e81(blank node)"
     "9a6603f7-169f-4129-89ec-62b48ff101aa(blank node)"
     "fd071213-7edb-48f9-b38a-9e2f3077a063(blank node)"
     "listMapAsSubject_X"
     "085347ab-5954-4413-89ed-65defc2723a4(blank node)"
     "7541d6b0-dfc3-40ba-a0ef-fa77f5553ca4(blank node)"
     "9d551482-8640-4605-a448-90a6046963e3(blank node)"
     "57bec0e9-00a5-43ed-89df-1f0ac3944b0e(blank node)"
     "4a2cafe4-085b-463e-8108-7041747905e4(blank node)"
     "844d7a67-53d3-4cd4-8469-ea09be558a82(blank node)"
     "a22a6c04-c5f2-40a4-a3e4-0399b21c2022(blank node)"
     "table"
     "thereExists"
     "bb2eba96-6b03-4c4c-8cab-062b94a8a2e7(blank node)"
     "f98908b7-52f3-44ce-a3ba-1f2a6753fc4d(blank node)"
     "41f1652a-22d2-46a5-b93c-e9295480367a(blank node)"
     "listMapAsObject_X"
     "faf61927-bbc8-4eb6-8e83-51fa2ed11d63(blank node)"
     "205e5ed2-e1c7-4ab4-94e3-55158d08adf1(blank node)"
     "noValuesOtherThan"
     "6045186a-34c1-4939-b2f1-ea484a24c32c(blank node)"
     "b46b8dc2-b0ad-4f28-94d6-def51169813c(blank node)"
     "344c55d6-8887-4cca-89ce-cc2d18edacbb(blank node)"
     "4e87681c-39a4-44a9-9b5a-790003246b43(blank node)"
     "566947b4-161a-440e-996d-71c26d776dd6(blank node)"
     "ac434a92-17c8-49a5-bf27-a98c84f3b626(blank node)"
     "af00895a-2acc-434f-bc20-52994dd840b5(blank node)"
     "a6f738c6-caeb-40b0-8bbc-d5a6583e63ef(blank node)"
     "isLiteral"
     "54963a74-f14c-44f5-a64a-4bfabed4eed0(blank node)"
     "7b098374-f87c-4242-97b8-3faaa296c8bc(blank node)"
     "8fcb1774-1707-407c-95da-9370c9543b27(blank node)"
     "3ea151f4-34ac-45bf-baf6-b675d75188c0(blank node)"
     "listContains_X"
     "86835f03-6081-431f-9030-c19c5894b27a(blank node)"
     "pow_X"
     "bcd39f06-0c99-4917-8d97-e1baab21c671(blank node)"
     "localname"
     "06147d7b-ff71-43aa-87ee-16b8c49e8970(blank node)"
     "asin"
     "7d28facc-577b-4d11-acac-85181af0bb6b(blank node)"
     "017ba545-4fd5-4b48-abbc-4dee76cac318(blank node)"
     "1851193b-c6e4-47e9-a9ea-1831d42cc171(blank node)"
     "le_X"
     "getInstance"
     "9c9809f7-8fc3-4d28-a7e5-129252391802(blank node)"
     "countUniqueMatches"
     "f2c7314a-bf5b-4ec4-b9fb-bee767b06e93(blank node)"
     "abs_X"
     "4931c75e-5b2b-4796-a60a-59829ebad499(blank node)"
     "print_X"
     "5e2141f6-5e05-467b-aa1f-f52ae3012501(blank node)"
     "f5d0e195-a46e-4ac7-8079-aad46d087ac4(blank node)"

**Comment by agabaldon** [comment]
@crapo: I only get the expected result:

`Query: "select ?x where {?x a <B>. filter not exists{?x a <C>}}"`
`     "x"`
`     "i1"`

**Comment by crapo** [comment]
@agabaldon , I don't think that was the original query in question. In your second comment you identify the SADL query in question to be:

Ask: select x where x is not a C.

The question is what this should translate to in SPARQL, and should it be:

Ask: "select ?x where { ?x <rdf:type> ?t . filter(?t != <C>)}".

This is what returns a lot of things besides i1, as I would expect because there are a lot of things which are not of type C. Your query in the previous comment is much more specific, "x is a B and x is not a C".

**Comment by crapo** [comment]
These two queries return exactly the same results. Is there some reason why one would be superior to the other?

 Ask: "select ?x where { ?x <rdf:type> ?t . filter(?t != <C>)}".
 Ask: "select ?x where {?x <rdf:type> ?t . filter not exists{?x <type> <C>}}".

One difference is that the second takes about twice as long to execute as the first (5 ms vs 2-3 ms, 2 runs).

**Comment by agabaldon** [comment]
I was referring to the query before your long comment.
I find using 'not exists' cleaner than using disequalities. It also works with multiple triples, etc.

**Comment by crapo** [comment]
These errors are believed to be fixed wtih PR #652 .

**Comment by agabaldon** [comment]
@crapo: if the "is not a" condition is not the last one, an exception occurs caused by a lingering dot:

Ask: select x where x is not a C and x is a B.

Query 'select ?x where { . ?x <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://sadl.org/neg_rule_test.sadl#B> . FILTER (!EXISTS { ?x <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://sadl.org/neg_rule_test.sadl#C> })}' failed: Encountered " "." ". "" at line 1, column 19.
Was expecting one of:
....

**Comment by agabaldon** [comment]
Thanks!
