### ISSUE TITLE
Extra and unneeded output in the console window

### ISSUE THREAD

**Issue by AbhaMoitra** [SemanticApplicationDesignLanguage/sadl#642]
I am running SADL version dated 3/26/2021 that I pulled from GIT. When I run my model I get a huge list of messages in the console window that seemed to be maybe related to debugging. Is there a way to turn them off? I was not getting these types of messages in earlier versions of SADL. Below is a screen capture of the initial output in the console window

![image](https://user-images.githubusercontent.com/28540315/113312429-47cadb00-92d8-11eb-9052-e39c63a9c2fc.png)

**Comment by crapo** [comment]
@AbhaMoitra , is the model something you can share? I don't recall seeing this so a minimal case would be helpful.

**Comment by AbhaMoitra** [comment]
@crapo : I think you should be able to replicate this issue with https://github.com/ml4ai/grasen-data/tree/master/SemanticModels/GraSEN. You only need the following 3 files from it: GrFNExtractionModel.sadl, PID—GrFN_grfn_jsonCombined.owl.sadl (these 2 files in ExtractedModels dir) and SemAnnotator.sadl which has rules and Ask etc. You can use OWL_DL_MEM_RULE reasoner or add the following 2 rules and then use OWL_MEM reasoner.

Rule Transitive1  // maybe I can drop this as I added Rule Transitive2
if inst is a cls and 
   cls is a type of CProgram
then inst is a CProgram.

Rule Transitive2
if inst is a cls and
   cls is a type of cls2
then inst is a cls2.  

Let me know if there are any questions. 
If you do not have access to the project link above, then let me know.

**Comment by crapo** [comment]
@AbhaMoitra , I am unable to access that repo.
![image](https://user-images.githubusercontent.com/1186278/113321806-f7587b00-92e1-11eb-8cb0-bf07a5abc0c5.png)

**Comment by AbhaMoitra** [comment]
@crapo you should now have access.

**Comment by crapo** [comment]
@AbhaMoitra , I need the built-ins strafter, strbefore. @agabaldon I had some code for an earlier version of strafter, but that may be out-of-date and I didn't have strbefore.

**Comment by agabaldon** [comment]
@crapo: I just checked the builtins in.

**Comment by crapo** [comment]
@AbhaMoitra , I don't reproduce the problem. This is the total output that I see when running the last query:
Inference of '/home/camfe/andy/ws/sadl/runtime-EclipseApplication2/Abha20210401/SemAnnotator.sadl' requested.
Query: select ?x ?xn where {?x a <LHS>. ?x <vname> ?xn. filter not exists{ ?x <notconstant> ?y}}
     "x","xn"
     "VARIABLE19","speed"
     "VARIABLE26","SetSpeed"
     "VARIABLE11","Ki"
     "VARIABLE10","Kp"
     "VARIABLE12","Kd"
     "VARIABLE4","setSpeed"
Derivation information requested but none available.

Are you running with a properties.log4j or some other logging control file that is turning on some debug? Can anyone else reproduce this problem?

**Comment by AbhaMoitra** [comment]
@crapo : Thank you for checking this out. Could you tell me where to look for properties.log4j?

**Comment by crapo** [comment]
See http://semanticapplicationdesignlanguage.github.io/sadl/KnownIssues.html.

**Comment by AbhaMoitra** [comment]
@crapo @agabaldon : The errors I was seeing were because I had been using strafter but did not see them when I updated from GIT and I had thought that strafter had been renamed to elementAfter. So I used elementAfter but that is for list. when I corrected this (now that strafter is also present) then the console output is as I expected.

**Comment by crapo** [comment]
@AbhaMoitra , @agabaldon sounds like more information should be provided by the list functions when the input isn't a list so that the source of the output is clear. It isn't possible, with the current structure of Jena BaseBuiltin class, to do anything other than write info about the error to the console without completely aborting inference.
