### ISSUE TITLE
New reasoner/translator pair not being found by service loader

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#644]
@tuxji , I'm stuck and really need some help. I've implemented a new reasoner/translator pair that extends the ones in the com.ge.research.sadl.jena-wrapper-for-sadl project. These are working and ready to create a PR except that they have stopped showing up in project properties dialog for choosing a reasoner and compatible translator. They were showing up and I can't seem to see any reason why they do no longer. There are reasoner/translators (implementations of IReasoner, ITranslator) in the com.ge.research.sadl.jena-wrapper-for-sadl project and in the com.ge.research.sadl.swi-prolog-plugin project. I can see that the correct content appears in the target jar file's META-INF/services/com.ge.research.sadl.reasoner.IReasoner and ....ITranslator files. And a project that had this new reasoner/translator pair selected still finds them and uses them without any problem.

The properties dialog editor content is populated by calls to ConfigurationManagerForIDE.getAvailableTranslators and  ConfigurationManagerForIDE.getAvailableReasoners, which use the java.util.ServiceLoader to get the classes, but for some reason it has stopped finding com.naturalsemanticsllc.sadl.translator.JenaAugmentedTranslatorPlugin and com.naturalsemanticsllc.sadl.reasoner.JenaAugmentedReasonerPlugin.

Note that when they were showing up, they were showing up when the SADL feature was installed, not just in the plugin development environment (once the new plugin project was added to the SADL feature). Now they show up in neither.

The code is pushed to the DefaultValues branch.

**Comment by tuxji** [comment]
@crapo , I checked out the DefaultValues branch and compared it to the development branch by running these commands:

```
git pull
git switch DefaultValues
git log origin/development..HEAD
git diff origin/development..HEAD
```

I suspect your problem was caused by using the "git merge" command repeatedly and having to fix some conflicts manually, introducing potential for mistakes each time.  I didn't look at the Java source file changes very closely, but there was a gratuitous change to com.ge.research.sadl.feature/feature.xml (reverting a previous change) and a lot of gratuitous changes to com.naturalsemanticsllc.sadl.augmented-jena-wrapper-for-sadl/META-INF/MANIFEST.MF (reversing some previous changes).  The feature.xml change only moved some lines and deleted a comment so it didn't really affect anything, but the MANIFEST.MF changes may have caused your problem.  Please replace both of these files with the same files from the development branch and test again.

When I work on a private branch (labeling it something like ji/sadl-630), I don't need to worry about anyone else making changes to my private branch.  In such a situation, I prefer to use "git rebase" instead of "git merge" to pull new commits from the public development branch into my private branch.  My history stays clean (there are no merge commits) and I have more control over my commits (I can combine two commits into one commit, etc.).  Just keep in mind you're rewriting history so "git rebase" is amazingly powerful but don't use it on public branches (<https://hackernoon.com/git-merge-vs-rebase-whats-the-diff-76413c117333>).

**Comment by crapo** [comment]
@tuxji , thanks for looking at this. I replaced the MANIFEST.MF and the feature.xml files with what is in development and rebuilt everything. This resulted in a failure to find the new reasoner/translator at all, even when the complete path and classname were known from the configuration.rdf file. Looking at MANIFEST.MF, it did not have the line

Eclipse-RegisterBuddy: com.ge.research.sadl

which is necessary so that the classloader used for this project is the same as the classloader that loaded ConfigurationManagerForIDE, from which the attempt to find the class originates. I added this line to MANIFEST.MF and rebuilt and then the reasoner/translator classes were found again when complete path and name were taken from the configuration.rdf file but they were not found by the serviceloader. 

I poked around some more and found this apparent anomaly that I don't understand. The target directory's com.naturalsemanticsllc.sadl.augmented-jena-wrapper-for-sadl-3.5.0.202104021606.jar file appears to contain, in the META-INF/services/ files the correct class names and path. However, in the target/classes/META-INF/services folder, the two files for IReasoner and ITranslator are empty. I suspect that these are the files that are used by the Eclipse environment when running in plugin development mode. I edited these files manually, adding the new class to each of the two files. Then when I ran the SADL IDE in Eclipse plugin development the classes were found by the service loader and populated correctly in the project properties popup dialog. 

I then compared the pom files for the three reasoner/translator projects and added what seemed to me to be minor, unrelated content that was in the other two poms:

      
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <workingDirectory>${project.build.testOutputDirectory}</workingDirectory>
        </configuration>
      </plugin>

Having done this, a Maven clean/install now results in content in the target/classes/META-INF/services files. However, as soon as I refresh the project in Eclipse the files are replaced with empty files. I thought perhaps this had something to do with the build.properties file, but that isn't any different from the projects that work. Nevertheless, I tried including the target/META-INF/services files in the binary build but to no avail. As soon as there's a refresh in eclipse the files are empty. Thoughts?

**Comment by crapo** [comment]
Some problems are probably not worth solving. If I move the new reasoner/translator classes into the existing JenaReasonerPlugin project then everything works as expected. I guess there is no compelling reason to have them in their own plugin.

**Comment by tuxji** [comment]
Thanks for finding a way to load the reasoner/translator classes.  I shouldn't have removed that `Eclipse-RegisterBuddy: com.ge.research.sadl` line from com.naturalsemanticsllc.sadl.augmented-jena-wrapper-for-sadl/META-INF/MANIFEST.MF (it was the only place I removed that line, fortunately).  I was sure that the `Bundle-ClassPath: .` line wasn't necessary (you usually add only jars to a classpath) and I thought the RegisterBuddy line wasn't needed either.  I found almost no documentation for what that line does except this page: <https://wiki.eclipse.org/Context_Class_Loader_Enhancements>.  I still don't think `Bundle-ClassPath: .` would have helped, but it's another line you can add back.

Concerning the target/classes/META-INF/services files, I don't know why they would become empty.  I compared the com.ge.research.sadl.jena-wrapper-for-sadl and com.naturalsemanticsllc.sadl.augmented-jena-wrapper-for-sadl projects' pom.xml and build.properties files.  I agree if you want to keep the com.naturalsemanticsllc.sadl.augmented-jena-wrapper-for-sadl project, you should try adding src/test/java back to its build.properties,

```
 1  ⋮    │source.. = src/main/java/
    ⋮ 1  │source.. = src/main/java/, src/test/java
```

and you should also try adding the surefire plugin back to its pom.xml.

If that doesn't work, I agree the problem isn't worth solving; just move the new reasoner/translator pair to the other com.ge.research.sadl.jena-wrapper-for-sadl project.

**Comment by crapo** [comment]
@tuxji , making those changes seems to allow the new plugin classes to be found by the service loader. Strange.

**Comment by crapo** [comment]
The augmented default values reasoner/translator pair disappeared from the service loader results once again. Moved them pair to the same project as the regular Jena reasoner/translator pair (com.ge.research.sadl.jena-wrapper-for-sadl). Here the service loader inclusion seems robust.
