### ISSUE TITLE
"Missing Constraint: Import-Package: javax.xml.stream"

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#648]
I have just started getting this popup:

![Screen Shot 2021-04-07 at 11 49 45 AM](https://user-images.githubusercontent.com/4990550/113922193-009b8900-97b5-11eb-98a2-fec57ffa4c80.png)

There may be an answer somewhere in this stackoverflow page: https://stackoverflow.com/questions/51094274/eclipse-cant-find-xml-related-classes-after-switching-build-path-to-jdk-10/53824670#53824670

**Comment by crapo** [comment]
@agabaldon , I have not seen this or been able to reproduce. Is this still an issue?

**Comment by agabaldon** [comment]
No, I think that was fixed/gone away. Closing...
