### ISSUE TITLE
length keyword for lists works in rules but not in queries

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#655]
Using "len is length of xl" in rules works fine, but in a query like:
   Ask: select x len where x is a TList and len is length of x.
the results are empty and it outputs a message saying "Unhandled filter type: length".

**Comment by crapo** [comment]
Queries in SPARQL use different functions that rules. I don't know that the Jena ARQ query engine has a built-in function for length of a list. I suppose that one could construct a SPARQL query that would get the length? Then the JenaTranslatorPlugin could be modified to generate that kind of query. Or one could add a SPARQL function to ARQ if it doesn't exist--I haven't ever done that.

**Comment by crapo** [comment]
@agabaldon , see for instance [https://stackoverflow.com/questions/9770807/getting-count-of-rdflist-using-sparql](https://stackoverflow.com/questions/9770807/getting-count-of-rdflist-using-sparql)

**Comment by agabaldon** [comment]
Oh I see. I assumed the built-ins can be used in queries. :-) In that case, I will do something else. Thanks!
