### ISSUE TITLE
Boolean default translation

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#662]
It seems that defaults of type boolean are not translated using typed boolean values, so they don't work. For example, 

`Thing is a class
described by p1 with values of type boolean.
p1 of Thing has default false.

i1 is a Thing. 

Ask: select x  where x is a Thing and x p1 false.`

Returns no results. And the rule encoding the default is:

`[http://sadl.org/query.sadl#Thing_p1_default_lvl0: (?i rdf:type http://sadl.org/query.sadl#Thing), noValue(?i,http://sadl.org/query.sadl#p1) -> (?i http://sadl.org/query.sadl#p1 false)]
`

**Comment by crapo** [comment]
Issue reproduced, looking into it.

**Comment by crapo** [comment]
Fix in PR #663.
