### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by AbhaMoitra** [SemanticApplicationDesignLanguage/sadl#729]
Here is the information that one of the ARCOS performers sent to me.  I myself have not verified this information. 

First, simply installing it has been a challenge. I have what (I think) is a working install (see below) but following the instructions at: http://semanticapplicationdesignlanguage.github.io/sadl/TempInstallInstructions.html fail (using the suggested Eclipse 2020-12 and Java 11 on Ubuntu 20.04 (using the latest SADL at https://github.com/SemanticApplicationDesignLanguage/sadl/releases/tag/v3.5.0-20201224 ) as the release already includes XText 2.23 and attempting to install the release over 2.24 results in a conflict during the SADL install:

![Boeing1](https://user-images.githubusercontent.com/28540315/126994375-cdcce70c-413b-45a2-b5ab-4cc194fc181d.png)

Continuing appears to succeed, but the resulting install will not load the SADL editor – attempting to do so results in the following error:
 
![Boeing2](https://user-images.githubusercontent.com/28540315/126994424-d85fe41f-ea65-44f0-85d6-329fce08a7c4.png)

Alternatively, the instructions include a suggestion to “install the latest bleeding edge automated build, go to Actions(https://github.com/SemanticApplicationDesignLanguage/sadl/actions), click on the latest (or any desired) result, scroll down to Artifacts, and download the ZIP file for installation.”

That doesn’t work as the Artifacts pane doesn’t allow downloads of the mentioned zip file (area circled below):

![Boeing3](https://user-images.githubusercontent.com/28540315/126994492-5d5ea669-3a66-4a13-a72b-52c14660bf2d.jpg)
 
Perhaps it does if you’re part of the Github project?

Anyway, I did manage to install the latest release in Eclipse 20-9 and Java 11.

**Comment by crapo** [comment]
I have verified in an incognito window that the artifact is not downloadable, although it is if I am logged into github as myself. @tuxji , is there any way around this? Perhaps we need to do a release a bit more often? @AbhaMoitra , I've kind of been hoping that the installation issues would be resolved by @tuxji as he seems much more knowledgeable about these issues. These temporary instructions referenced were meant to be temporary, remaining in the documentation only until the installation issues were resolved....

**Comment by tuxji** [comment]
Discussion [here](https://github.community/t/public-read-access-to-actions-artifacts/17363) confirms you must be logged into GitHub as a user to download a workflow artifact.  Empirically, I've tried to download a workflow artifact without logging into GitHub as a user and no way seems to work.  My conclusion is that we need to do a release more often as well as fix any installation issues installing a new release.

**Comment by tuxji** [comment]
I've modified the SADL codebase and the GitHub workflows so they also build and upload ready to run out of the box SADL-Eclipse products for Linux, MacOS, and Windows platforms as well as the SADL update p2-repository. I've built a new SADL release with this automated workflow. People can install a functional SADL IDE simply by unzipping the appropriate Eclipse product for their platform, running its executable launcher binary, and then importing a SADL project into their SADL-Eclipse's workspace. Then when a new SADL release is available, people can either replace their SADL-Eclipse product or update their SADL-Eclipse product using "Help -> Install New Software..." and the new SADL update p2-repository's zip archive.  Eventually people will be able to run "Check for Updates" in their SADL-Eclipse product as a third method, but that will have to wait for some additional changes.

**Comment by tuxji** [comment]
A new SADL release is available now.  This release corrects SADL's explicitly versioned dependency on Xtext 2.24.0. SADL should now install in any recent Eclipse version, not only Eclipse 2020-12, and use any recent Xtext version compatible with that Eclipse version, not only Xtext 2.24.0.  This release should fix this issue's installation problems, I believe.

**Comment by crapo** [comment]
I think this issue can be closed, do you agree @tuxji ?

**Comment by tuxji** [comment]
Yes, I agree and I will close this issue.
