### ISSUE TITLE
NumericConstant creation

### ISSUE THREAD

**Issue by NAVEENKUMARSKPN** [SemanticApplicationDesignLanguage/sadl#758]
Hi Team ,

is it possible to create a numeric constant without creatin a class.
 
Eg:
Threshold has a single value 450.

**Comment by crapo** [comment]
@NAVEENKUMARSKPN , I forgot to respond to this. Maybe you've worked out a solution? I would create a class NumericConstant, subclass of sadlimplicitmodel:UnittedQuantity. Then you could say
Threshold is a NumericConstant, has ^value 450.
To use it in an expression you would say "^value of Threshold".
You could give it units if appropriate. Or you could create your own class and give it a property for the value.

**Comment by NAVEENKUMARSKPN** [comment]
Yes  @crapo  I got a solution exactly what you mentioned with UnittedQuantity I am able to create a constant

Thanks!!!
