### ISSUE TITLE
Errors in Eclipse SADL dev environment

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#760]
SADL built without problems on command line, but Eclipse shows 26 errors saying:

Plugin execution not covered by lifecycle configuration: org.eclipse.tycho:target-platform-configuration:2.4.0:target-platform (execution: default-target-platform, phase: initialize)

**Comment by crapo** [comment]
I get the same thing. However, it still runs in the development environment.

**Comment by agabaldon** [comment]
I tried it and it runs, but the buitins defined in jena-wrapper-for-sadl are missing from the implicit model.

**Comment by agabaldon** [comment]
The missing builtins problem is fixed with today's update from @tuxji so I think we can close this one.
