### ISSUE TITLE
Is there a tool for creating SADL instead of Eclipse

### ISSUE THREAD

**Issue by NAVEENKUMARSKPN** [SemanticApplicationDesignLanguage/sadl#779]
Hi Team,

I would like to know is there any other tool that allows me to create sadl from web (UI) instead of going with Eclipse IDE 

Thanks

**Comment by crapo** [comment]
There is a browser-based UI for SADL. The documentation hasn't been updated yet, and it is experimental. Older documentation is on this file: https://github.com/SemanticApplicationDesignLanguage/sadl/blob/c3e867b5ff8e4e6873e58f47aecb1b7609e0811f/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl3.documentation/WebSite/sadl3/WebSADL.html.

**Comment by crapo** [comment]
@NAVEENKUMARSKPN , I've added the documentation of WebSADL at http://semanticapplicationdesignlanguage.github.io/sadl/WebSADL.html. Note that there are some know issues with the latest docker image but the one tagged 0.2.0-next.b2c251dd seems to work OK.
