### ISSUE TITLE
User-defined data type translation to OWL

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#791]
### Discussed in https://github.com/SemanticApplicationDesignLanguage/sadl/discussions/789

<div type='discussions-op-text'>

<sup>Originally posted by **AbhaMoitra** September 15, 2021</sup>
@glguy brought this to my attention.

I am using a user-defined data type in SADL as follows
      Range is a type of float [0,1].
The OWL that is generated is as follows

  <rdfs:Datatype rdf:ID="Range">
    <owl:equivalentClass>
      <rdfs:Datatype>
        <owl:withRestrictions rdf:parseType="Collection">
          <rdf:Description>
            <xsd:maxInclusive rdf:datatype="http://www.w3.org/2001/XMLSchema#float"
            >1</xsd:maxInclusive>           
            <xsd:minInclusive rdf:datatype="http://www.w3.org/2001/XMLSchema#float"
            >0</xsd:minInclusive>
          </rdf:Description>
        </owl:withRestrictions>
        <owl:onDatatype rdf:resource="http://www.w3.org/2001/XMLSchema#float"/>
      </rdfs:Datatype>
    </owl:equivalentClass>
  </rdfs:Datatype>

However the following is what works in Protege; notice the extra "</rdf:Description> <rdf:Description>"

  <rdfs:Datatype rdf:ID="Range">
    <owl:equivalentClass>
      <rdfs:Datatype>
        <owl:withRestrictions rdf:parseType="Collection">
          <rdf:Description>
            <xsd:maxInclusive rdf:datatype="http://www.w3.org/2001/XMLSchema#float"
            >1</xsd:maxInclusive>
          </rdf:Description>
          <rdf:Description>
            <xsd:minInclusive rdf:datatype="http://www.w3.org/2001/XMLSchema#float"
            >0</xsd:minInclusive>
          </rdf:Description>
        </owl:withRestrictions>
        <owl:onDatatype rdf:resource="http://www.w3.org/2001/XMLSchema#float"/>
      </rdfs:Datatype>
    </owl:equivalentClass>
  </rdfs:Datatype>

Should SADL be generating OWL differently or should Protege be ok with what SADL is generating?

</div>

**Comment by crapo** [comment]
@AbhaMoitra ,  @glguy, this is fixed in PR #792 .

**Comment by AbhaMoitra** [comment]
@crapo : thank you very much!
