### ISSUE TITLE
Fix TDB persistence, consistency of use of SadlJenaModelGetter, SadJenaModelGetterPutter

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#794]
After discussions with @agabaldon and some investigation, it appears that 1) TDB persistence is somewhat broken, and 2) use of the classes SadlJenaModelGetter and SadlJenaModelGetterPutter is inconsistent. Some of this probably stems from moving to Jena 3, which had some changes in model writing/reading that also allowed for more serialization formats. The objective is for all persisting and retrieving of OWL models to go through these classes so that code that deals with various triple store mechanisms is isolated and easily extended to support additional triple stores.

**Comment by crapo** [comment]
@agabaldon , I have started this refactoring and pushed progress to-date to branch GH-794. I've set up the Java Interface classes, the classes for getter/putter for Jena file-based, and am working on getter/putter for TDB. I have not yet deleted the old getter/putter classes and haven't worked on external OWL files yet. Feel free to take a look and comment.

**Comment by crapo** [comment]
@agabaldon , I have removed all references to the old getter/putter classes, but have not deleted them. I've updated all use of gettter/putter classes to use the new ones. All tests pass, but I'm not sure what isn't tested. I consider this refactoring complete and will now work on documenting the approach and on testing.

**Comment by crapo** [comment]
@agabaldon , I renamed SadlSerializationFormat class to SadlPersistenceFormat, since triple stores aren't serialization. Moved to persistence package.

**Comment by crapo** [comment]
@agabaldon , documentation has been added to Developer Resources, see [http://semanticapplicationdesignlanguage.github.io/sadl/developer/ModelPersistence.html](http://semanticapplicationdesignlanguage.github.io/sadl/developer/ModelPersistence.html).

**Comment by agabaldon** [comment]
Great! I'll trying using the new classes.

**Comment by agabaldon** [comment]
@crapo, SadlJenaModelGetterPutter has been replaced by SadlJenaFileGetterPutter, correct? 
What is the "format" string argument one should pass to the SadlJenaFileGetterPutter constructor? For example, in replacing the line: 
  spec.setImportModelGetter(new SadlJenaModelGetterPutter(spec, getOwlModelsFolder()));
by
  spec.setImportModelGetter(new SadlJenaFileGetterPutter(getConfigurationManager(), ??format??));

[The example is from the AnswerCurationManager in the ASKE sys]

**Comment by agabaldon** [comment]
The method 
  public OntModel getOntModel(String publicUri, String serializedGraph, Scope scope, String format)  
in ConfigurationMangaerforIDE is no longer there. It is called by the TextProcessor in ASKE. What should be used instead?

**Comment by crapo** [comment]
@agabaldon , I think that it would be helpful to look at the code changes in SADL when considering how to update ASKE. The ConfigurationManager has new methods getSadlModelGetter and getSadlModelGetterPutter that can be called to create the appropriate getter/putter instances. These only take format as argument, where format is the string from the preference setting, which should also be one of the public static final strings in SadlPersistenceFormat, e.g., "RDF/XML ABBREV". 

The ConfigurationManagerForIDE method getOntModel(String publicUri, String serializedGraph, Scope scope, String format) converted a serialized OWL model as a String to a Jena OntModel. It wasn't used by SADL so I removed it. It should probably be put back in and should just call a method that should be added to SadlModelGetter to convert a serialized model as a String to an OntModel. The method belongs in this class, just as CharSequence getOntModelAsString(...) does, so that it can be used by any of the subclasses for specific formats.

**Comment by crapo** [comment]
@agabaldon , can this issue be closed? If not, what action can be taken?

**Comment by agabaldon** [comment]
I think so, but like with GH-808, we need to make sure things don't break after merging into development.
