### ISSUE TITLE
Long build time

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#796]
This is not really an issue per se, but with the addition of 'product', building SADL takes very long. Could we use "profiles" as described here: https://stackoverflow.com/questions/8304110/skip-a-submodule-during-a-maven-build to skip product when it's not a CI build? Maybe other modules can also be skipped when doing development, e.g. server?

**Comment by tuxji** [comment]
I read your linked article and it seems profiles have a drawback: when you want to run Maven plugins such as maven-release-plugin on all submodules, someone said that maven-release-plugin doesn't update the version string of submodules that are hidden behind a profile switch, resulting in sub-modules with different version strings than the rest of the project.  Still, skipping `product` would indeed save developers between 40 and 60 seconds when building SADL.  Here's how long a full build takes on my laptop:

```shell
$ mvn package -Dtycho.localArtifacts=ignore
[INFO] Total time:  02:25 min
```

If I exclude com.ge.research.sadl.product from the build with the -pl flag, I do indeed save 40 seconds:

```shell
$ mvn package -pl \!com.ge.research.sadl.product -Dtycho.localArtifacts=ignore
[INFO] Total time:  01:45 min
```

You could create a shell alias in your ~/.bash_aliases to build sadl as quickly as possible:

```bash
alias mvnsadl='mvn package -pl !com.ge.research.sadl.product -Dtycho.localArtifacts=ignore'
```

Would that be as good as defining a profile without risking the profile's drawback?

**Comment by agabaldon** [comment]
That's too bad. It looked like a simple solution but it seems that even after the years since that post, profiles are still risky (https://maven.apache.org/guides/introduction/introduction-to-profiles.html#profile-pitfalls). The alias approach works for me. Thanks!

**Comment by agabaldon** [comment]
On my laptop (mvn install -Dtycho.localArtifacts=ignore -Dmaven.test.skip):
[INFO] com.ge.research.sadl.product ....................... SUCCESS [10:51 min]
...
[INFO] Total time:  17:51 min

Maybe I have some other additional problem in my setup or just a slow laptop.

**Comment by tuxji** [comment]
I have a big and heavy laptop.  My laptop was faster than GitHub's CI runner, but GitHub's CI runner still took only a few minutes in its build SADL step:

```
[INFO] com.ge.research.sadl.product ....................... SUCCESS [01:06 min]
..
[INFO] Total time:  03:41 min
```

Yeah, your laptop looks like it's unusually slow.

**Comment by crapo** [comment]
@agabaldon , @tuxji , is there some follow-up for this issue? I'm trying to see which issues need action to resolve....
