### ISSUE TITLE
SADL build issue

### ISSUE THREAD

**Issue by NAVEENKUMARSKPN** [SemanticApplicationDesignLanguage/sadl#804]
Hi Team ,

I was trying to build sadl code into my new workspace..while trying to execute SADL mvn clean install.launch it was throwing error while building com.ge.research.sadl.ide

I am sharing the exception 

> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary for com.ge.research.sadl.parent 3.5.0-SNAPSHOT:
> [INFO] 
> [INFO] com.ge.research.sadl.parent ........................ SUCCESS [  0.919 s]
> [INFO] com.ge.research.sadl.reasoner ...................... SUCCESS [  0.248 s]
> [INFO] reasoner-api ....................................... SUCCESS [  7.696 s]
> [INFO] reasoner-impl ...................................... SUCCESS [  2.244 s]
> [INFO] com.ge.research.jena ............................... SUCCESS [  2.947 s]
> [INFO] com.ge.research.sadl.xtextgenerator ................ SUCCESS [ 13.110 s]
> [INFO] com.ge.research.sadl.errorgenerator ................ SUCCESS [  0.424 s]
> [INFO] com.ge.research.sadl ............................... SUCCESS [01:24 min]
> [INFO] com.ge.research.sadl.jena .......................... SUCCESS [  4.465 s]
> [INFO] com.ge.research.sadl.jena-wrapper-for-sadl ......... SUCCESS [  3.466 s]
> [INFO] com.ge.research.sadl.ide ........................... FAILURE [  5.031 s]
> [INFO] com.ge.research.sadl.ui ............................ SKIPPED
> [INFO] com.ge.research.sadl.applications .................. SKIPPED
> [INFO] com.ge.research.sadl.externalmodels ................ SKIPPED
> [INFO] com.ge.research.sadl.importer ...................... SKIPPED
> [INFO] com.ge.research.sadl.importer.ide .................. SKIPPED
> [INFO] com.ge.research.sadl.importer.ui ................... SKIPPED
> [INFO] com.ge.research.sadl.perspective ................... SKIPPED
> [INFO] com.ge.research.sadl.swi-prolog-plugin ............. SKIPPED
> [INFO] com.ge.research.sadl.testsuite ..................... SKIPPED
> [INFO] com.ge.research.sadl.testsuite.ide ................. SKIPPED
> [INFO] com.ge.research.sadl.testsuite.ui .................. SKIPPED
> [INFO] com.ge.research.sadl.feature ....................... SKIPPED
> [INFO] com.ge.research.sadl.importer.tests ................ SKIPPED
> [INFO] com.ge.research.sadl.importer.ui.tests ............. SKIPPED
> [INFO] com.ge.research.sadl.product ....................... SKIPPED
> [INFO] com.ge.research.sadl.server ........................ SKIPPED
> [INFO] sadlserver-api ..................................... SKIPPED
> [INFO] sadlserver-impl .................................... SKIPPED
> [INFO] com.ge.research.sadl.target ........................ SKIPPED
> [INFO] com.ge.research.sadl.tests ......................... SKIPPED
> [INFO] com.ge.research.sadl.testsuite.tests ............... SKIPPED
> [INFO] com.ge.research.sadl.testsuite.ui.tests ............ SKIPPED
> [INFO] com.ge.research.sadl.ui.tests ...................... SKIPPED
> [INFO] com.ge.research.sadl.update ........................ SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  02:44 min
> [INFO] Finished at: 2021-10-04T14:11:01+05:30
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.eclipse.xtend:xtend-maven-plugin:2.24.0:compile (default-compile) on project com.ge.research.sadl.ide: Error compiling xtend sources in 'C:\Users\Naveen\git\sadl3\com.ge.research.sadl.parent\com.ge.research.sadl.ide\src'. -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <args> -rf :com.ge.research.sadl.ide

Eclipse - 2020-09 (4.17.0)
Maven  - 3.8,3
Java - 11
OS - Windows server 2012 R2

Please help me on this Thanks!!

**Comment by NAVEENKUMARSKPN** [comment]
I got http://semanticapplicationdesignlanguage.github.io/sadl/developer/Sadl3BuildInstructions.html this docs .... And now its builded successfully

Thanks !!

**Comment by tuxji** [comment]
Good.  The key is to run "mvn clean" and "mvn install" separately, not on the same command line.
