### ISSUE TITLE
Inefficiency in DeclarationExtensions.getOntConceptType?

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#819]
Not sure I have understood this correctly, but while investigating unexpectedly slow model processing I think I observe that when getOntConceptType in DeclarationExtensions is called with a SadlResource in a class definition a lot of redundant computing can occur.

Consider this case. a model states "Element as a type of ENTITY.", where ENTITY is defined in a different model (in a different project in this case) as "ENTITY is a type of THING." where "THING is a class."

For semantic highlighting and for model processing, the concept type of Element is needed. Hence:

1. getOntConceptType(Element) is called, which is in a SadlSimpleTypeReference with type ENTITY
2. getOntConceptType(ENTITY) is called and proceeds to check if ENTITY is CLASS_PROPERTY
3. getOntConceptType(THING) is called and eventually reaches matching case and returns CLASS
4. getOntConceptType(THING) is called again to check if concept type of ENTITY is DATATYPE_PROPERTY
5. This repeats with checks for ANNOTATION_PROPERTY, RDF_PROPERTY, and DATATYPE
6. As none of these cases succeed, it falls through to return CLASS for ENTITY
7. getOntConceptType(ENTITY) is called to check if ENTITY is a DATATYPE_PROPERTY
8. This causes steps 3 through 7 to repeat
9. Steps 3 through 7 repeat again for ANNOTATION_PROPERTY, RDF_PROPERTY, and DATATYPE

Thus getOntConceptType(THING) is called 5 times for each of 5 calls to getOntConceptType(ENTITY).

I'm not sure how to modify the DeclarationsExtensions code so that this doesn't happen. Some kind of caching might help? It's written in Xtend, with which I'm not intimately familiar.
@tuxji , does anyone at GE know Xtend well enough to suggest an improvement?
@kittaakos , would you be willing to look at this in the spirit of Open Source contribution?

**Comment by tuxji** [comment]
@crapo , Xtend is a statically-typed programming language which translates to Java source code. Syntactically and semantically Xtend takes its root from the Java programming language with some improvements to make its syntax easier.  I haven't read the Xtend reference, but I could look at an Xtend method and understand its Java-like code well enough to make a simple change.  If the change wasn't simple enough, I could skim the Xtend reference [docs](https://www.eclipse.org/xtend/documentation/index.html) for what I needed to know. 

Please tell me where to set a breakpoint to stop at step 1 or 2 (the place where the recursive loop starts).  Is it somewhere in [DeclarationExtensions.xtend](https://github.com/SemanticApplicationDesignLanguage/sadl/blob/development/sadl3/com.ge.research.sadl.parent/com.ge.research.sadl/src/com/ge/research/sadl/model/DeclarationExtensions.xtend)?

**Comment by crapo** [comment]
@tuxji , yes, the issue is in DeclarationExtensions.xtend. I've modified this and a lot of other xtend code and have some familiarity with Xtend. The problem, specifically, is that I think a reasonable approach is to cache the type with SadlResource as key, but to do that I need to intercept the returned value from the method getOntConceptType to add it to the cache. The switch statement starting ~line 266 in the xtend code implicitly sets the returned value of type OntConceptType and I don't see a) how to capture that value which is going to be returned and b) cache it before the actual return. In the debugger I can see the implicit variable holding the value to be returned, but it's just implicit as far as I know. I've done some perusing of documentation on Xtend switch statements, but didn't find anything I recognized as a viable approach. I think that DeclarationExtensions needs to have a Map to cache OntConceptType by SadlResource, check the cache first and return the value, if cached, before computing a value, and possibly have a method to clear the cache if there are situations where the duration of a DeclarationExensions instance outlives the validity of the cache. I could recode it in Java, but would prefer not to.

**Comment by crapo** [comment]
@tuxji , actually, I probably do know how to do what I want to do. Don't worry about spending any time on this.

**Comment by crapo** [comment]
@tuxji , the cache appears to significantly improve performance. I haven't pushed it yet, still exploring error collection. I wanted to run on a single project but it appears that getArguments (in SADLCli) has been modified so that any "-cleanBuild" or "-build" args will result in a fatal error as the next argument, the project name, causes an exception to be thrown. Do you only plan to support "-cleanBuild" with no following project, meaning I guess clean build all?

**Comment by tuxji** [comment]
If you want to build only one project, you can import only that one project (assuming you're using an empty workspace).  Our use case is that SADLCli will be running inside a Docker image with an empty workspace.  The workspace will be empty every time you start the Docker container, so you always need an "-import" arg followed by an individual project or an "-importAll" arg followed by a directory.  Since you can replace an "-importAll" arg with many "-import" args importing only specific projects, I figured we only needed "-cleanBuild" or "-build" with no following project, meaning clean build or build everything imported into the initially empty workspace.  Do you want to "-importAll" a tree of projects and then build only one project (even if it uses dependencies from the other projects)?  Please discuss if you think we really need to support importing more projects than we want to build, or you can temporarily change your copy of SADLCli.java to restore that project argument for your testing.

**Comment by crapo** [comment]
@tuxji , I just wanted a faster processing to get to the error accumulation. I don't question your use case. Thanks!

**Comment by crapo** [comment]
@tuxji , I haven't had any success getting the errors after the XtextBuilder.build returns. I'm starting to despair of finding a way to do that. I'm also wondering if it wouldn't be useful to have the errors and warnings come out earlier in the process. One approach would be to collect the ValidationAcceptors used during model processing and then retrieve them after the build completes and get the errors from each. Another would be to have the instance of PrintProgressMonitor available to the model processor and have errors and warnings output via that instance. I think this might be undesirable because there may be errors on an earlier pass that aren't there after a later pass. Thoughts?

**Comment by tuxji** [comment]
Does the PrintProgressMonitor interface have an API for accumulating errors, are you talking about calling instanceof on the monitor and casting it to a specific implementation class, or are you simply talking about buffering any output printed, getting the output later, and displaying that output as errors and warnings?  I would think if the PrintPogressMonitor doesn't have an error accumulation API, it may be the wrong place to accumulate errors, especially if later passes fix some errors from earlier passes.  

The other approach (collecting the ValidationAcceptors used during model processing and getting the errors from each) sounds more promising, although I don't know how to do that either.  Before you try that approach, however, please push your cache changes.  I'd like to start running SADLCli on RACK in GitHub Actions soon.

**Comment by crapo** [comment]
@tuxji , I've pushed the caching in DeclarationExtensions. This is not ready to be merged into development. While this should be safe for use by SADLCli where presumably nothing is changing in the .sadl files, there may be situations in the IDE, when editing, when the cache will be invalid and should be cleared. This still needs to be investigated.

I'm thinking that we wouldn't accumulate errors, since some errors might happen on early passes for a given XtextResource but  not be present on a subsequent pass. Rather I'm thinking we would keep a map of errors keyed by XtextResource so that we'd have the latest errors for each. It may be sufficient to just keep the ResourceSet for each project as I think the errors can be retrieved from the ResourceSet. I just haven't figured out how to get the ResourceSet after the build completes.

**Comment by tuxji** [comment]
Resolved in PR #827
