### ISSUE TITLE
Possible invalid `owl:oneOf` output

### ISSUE THREAD

**Issue by kquick** [SemanticApplicationDesignLanguage/sadl#823]
Given the following SADL input:
*  https://github.com/ge-high-assurance/RACK/blob/0b30cc8878485d2e902eee2021de993544e50562/RACK-Ontology/ontology/AGENTS.sadl#L26-L31
* https://github.com/ge-high-assurance/RACK/blob/182d0483a73cdc221c692c71e0d4e64f92f5079a/RACK-Ontology/ontology/SOFTWARE.sadl#L61

The output specifies:
* https://github.com/ge-high-assurance/RACK/blob/182d0483a73cdc221c692c71e0d4e64f92f5079a/RACK-Ontology/OwlModels/SOFTWARE.owl#L54-L66

Per https://www.w3.org/TR/owl-ref/#EnumeratedClass, it would seem that a `oneOf` enumeration can only be associated with (a) *instances* of the class, or (b) literals (https://www.w3.org/TR/owl-ref/#EnumeratedDatatype), but not subclasses as described in the output above.

Perhaps a more acceptable alternative output would be the creation of an internal `owl:equivalentClass` that is the `owl:unionOf` the possible range classes along with one or more `owl:disjointWith` declarations to indicate the range can be only one of the equivalent class targets (https://www.w3.org/TR/owl-ref/#disjointWith-def).

**Comment by crapo** [comment]
@kquick , this is a gap in validation and the statement should generate an error since, as you say, "one of" should only allow instances of classes.

The correct way to say what was presumably intended is:

`sw:performedBy of PACKAGE only has values of type {Ag:PERSON or Ag:ORGANIZATION}.`

which yields the OWL class definition:

>   <owl:Class rdf:ID="PACKAGE">
    <rdfs:subClassOf>
      <owl:Restriction>
        <owl:allValuesFrom>
          <owl:Class>
            <owl:unionOf rdf:parseType="Collection">
              <rdf:Description rdf:about="AGENTS#PERSON"/>
              <rdf:Description rdf:about="AGENTS#ORGANIZATION"/>
            </owl:unionOf>
          </owl:Class>
        </owl:allValuesFrom>
        <owl:onProperty>
          <owl:ObjectProperty rdf:ID="performedBy"/>
        </owl:onProperty>
      </owl:Restriction>
    </rdfs:subClassOf>
    <rdfs:comment xml:lang="en">ACTIVITY of running a PACKAGER to produce a package FILE</rdfs:comment>
    <rdfs:subClassOf rdf:resource="FILE#FILE_CREATION"/>
  </owl:Class>

**Comment by crapo** [comment]
The PR for this issue has been merged. Closing issue.
