### ISSUE TITLE
Issue in translation to OWL

### ISSUE THREAD

**Issue by AbhaMoitra** [SemanticApplicationDesignLanguage/sadl#851]
I am using SADL version 3.5.0.202111302056 and in the case when in a SADL file you have 
      prop1: domain1 -> range1
      prop1: domain2 -> range2

The SADL properties have unchecked "Translate multiple-class domain or range as union class (owl:unionOf)"  then the OWL file has the following

  <owl:ObjectProperty rdf:ID="prop1">
    <rdfs:range rdf:resource="#range1"/>
    <rdfs:domain rdf:resource="#domain1"/>
    <rdfs:range rdf:resource="#range2"/>
    <rdfs:domain rdf:resource="#domain2"/>
  </owl:ObjectProperty>

From the owl file you cannot "pair up" domain1 with range1 etc. And you would also get the same OWL translation from a semantically different SADL file. 

An example of this is present in https://github.com/ge-high-assurance/RACK/blob/master/LM-Ontology/ontology/LM.sadl where prop1 is "target".

**Comment by crapo** [comment]
@AbhaMoitra , I'm unaware of any expressivity in OWL that would allow you to "pair up" subclasses of the domain class with subclasses of the range class, whether expressed as a single domain union class and single range union class or not. 

If you want to do this you need to use property restrictions, e.g., 

prop1 of domain1 only has values of type range1.
prop1 of domain2 only has values of type range2.

Note that these two statements in no way affect the domain and range of the property. They just put on additional owl:allValuesFrom constraints.

**Comment by AbhaMoitra** [comment]
@crapo: thank you. I used the property restriction and then all the information was available in the OWL file.
