### ISSUE TITLE
SADL Query Language Limitation

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#874]
Given this model and queries, the first query works, the second does not. Processing of the second query is inadequate.

 Part is a class
          described by partID with values of type string
          described by processing with values of type Process.

 Process is a class
          described by temperature with values of type Temperature.

 Temperature is a type of UnittedQuantity.

 p1 is a Part
          partID "123"
          processing (a Process temperature (a Temperature ^value 100 unit "C")).
  
 // what is the temperature of processing of p1?
 Ask: select x where x is the temperature of processing of p1.

// what is the temperature of processing of (a Part partID "123")?
 Ask: select x where x is the temperature of processing of (a Part with partID "123").

**Comment by crapo** [comment]
@agabaldon , I believe this is fixed with PR #875. Added tests for your case and more complex one with longer property chain.

**Comment by agabaldon** [comment]
Great! Will try it now. Thanks.
