### ISSUE TITLE
Queries not working when using TDB.

### ISSUE THREAD

**Issue by agabaldon** [SemanticApplicationDesignLanguage/sadl#876]
Just using a minimal project with model

B is a class.
i1 is a B.

Ask: select x where x is a B.

Output:

Reasoner family: Jena-Based (com.ge.research.sadl.jena.reasoner.JenaReasonerPlugin), version date 12 April 2021.
Query: select x where rdf(x, rdf:type, test:B)
Inference result 1 is empty

**Comment by crapo** [comment]
Confirmed results.

**Comment by crapo** [comment]
This appears to be an issue with beginning and ending transactions. The begin transaction code is commented out, but maybe there's an isInTransaction method that can be used to make it more robust

**Comment by crapo** [comment]
Actually,  getter/putter for TDB interactions were never completed after refactoring in #794 .

**Comment by crapo** [comment]
@agabaldon , I believe this is fixed with PR #880. Please close when you are satisfied.
