### ISSUE TITLE
Enabling external datasources

### ISSUE THREAD

**Issue by amarbanerjee23** [SemanticApplicationDesignLanguage/sadl#900]
Currently, SADL only supports jena/semTK data store. Is is possible to plug-in external sources like graphdb/stardog and import ontologies in SADL project?

**Comment by crapo** [comment]
OWL files in standard formats can be imported into any SADL project, see [Importing Files into SADL](http://semanticapplicationdesignlanguage.github.io/sadl/ImportFilesToSadl.html). To have an external triple store other than those currently supported act as the repository into which generated OWL files are inserted and needed OWL files are pulled would require additional development work, see [Connecting the SADL IDE with Persistent Storage of OWL Models and Rules](http://semanticapplicationdesignlanguage.github.io/sadl/developer/ModelPersistence.html).

**Comment by amarbanerjee23** [comment]
Thanks a lot Andrew. This helps a lot. Any idea if any demo implementation is available in the codebase?

Cheers,
Amar

**Comment by crapo** [comment]
The Jena TDB and the SemTK getter/setters both provide examples of extending the base classes to support an external repository. @agabaldon  has implemented the SemTK connections.

**Comment by crapo** [comment]
@amarbanerjee23 , can this be closed now?

**Comment by amarbanerjee23** [comment]
sure Andrew.
