### ISSUE TITLE
Abbreviated conjunction of properties and/or property chains in queries

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#904]
It is normal in English to abbreviate conjunctions in the following way:
- "temperature and volume of a part" instead of "temperature of a part and volume of the part"
- "temperature and volume of the processing of a part" instead of "temperature of the processing of a part and volume of the processing of the part"
The SADL model processing can handle this construct and it makes sense to do so at least when part of a query. It is less clear where else this might make sense, but the query constraint can be relaxed in the future if found to be too restrictive.

**Comment by crapo** [comment]
@agabaldon , this is implemented in branch GH-904. Please check it out and make sure it works as expected in SADL and Dialog.

**Comment by agabaldon** [comment]
Thanks @crapo. My use case is slightly more complicated and has a subclass of Process. Something like:

Process is a class
 	described by processNum with a single value of type string 	.
 
 SubProcess is a type of Process
  	described by temperature with values of type UnittedQuantity
 	described by volume with values of type UnittedQuantity
 	described by pressure with values of type UnittedQuantity .

The ask statement  
  Ask: temperature and processNum of the processing of part1.
shows an error "Unexpected non-proxy".

**Comment by crapo** [comment]
@agabaldon , that I have fixed (not checked in). You're aware that implied properties aren't implemented for queries? Just in case you expected 

"Ask: temperature and processNum of the processing of part1." 

to return the value and units of temperature.

**Comment by agabaldon** [comment]
Great. Thanks!

**Comment by crapo** [comment]
@agabaldon , do you expect/do you want the query in question to return the value and units of temperature, as opposed to what would be, in any instance data, the bnode that is the instance of temperature?

**Comment by agabaldon** [comment]
Yes. I already have code in JBDIP to deal with that. It actually helps because this way, the pseudorules have a single then triple (in the case of a simple query) with the relevant property (e.g. temperature) in it.

**Comment by crapo** [comment]
Interesting. Making implied properties work for SADL queries and tests is on my to-do list. Do you foresee a problem in the future when implied properties for queries and tests (as well as rules) are handled by JBSMP and the SADL IFTranslator?

**Comment by agabaldon** [comment]
That will require changes in the current JBDIP but I think that extension makes sense. Not necessary for immediate project needs though.

**Comment by agabaldon** [comment]
Is it checked in?

**Comment by crapo** [comment]
I just pushed updates to handle more complex situation to GH-904 branch. I have not created a PR. I think we need to make sure it handles all of your cases first.

**Comment by agabaldon** [comment]
I tried the query 

what is temperature and processNum of the processing of (a Part with partID "123")? 

and the thenObj I get after the call to processAsk in JBDMP (line 906 in SGH-784 branch) is:

select v0 v1 v2 v3 where and(rdf(v0, propchains:processing, v1), and(rdf(v1, propchains:temperature, v2), rdf(v1, propchains:processNum, v3)))

It is missing the triple rdf(v0, propchains:partID "123").

You can see the same result using a SADL query.

**Comment by crapo** [comment]
@agabaldon , nice new variation! Do you have any other variations that you can give me now so I can create a better set of test cases?

**Comment by agabaldon** [comment]
I think that's the most complex one I have right now. Combines abbreviated property chains and indirect reference to the object(s) through properties. Maybe another variation is just saying "a Part" to get answers for all the Part instances.

**Comment by crapo** [comment]
@agabaldon , I've generalized a bit more to handle this more complex case. Added more test to verify behavior with different constructs, both with and without indefinite and definite articles used in translation. Pushed to GH-904

**Comment by crapo** [comment]
@agabaldon , please let me know when you feel this can be proposed as a PR to merge with development.

**Comment by agabaldon** [comment]
I'm trying it and it looks good so far, but I ran into another problem that is preventing me from running a full test.

**Comment by agabaldon** [comment]
Well, strange. After pulling this branch, the method getUniquePropertyRange stopped working. The method calls getTheJenaModel().listStatements which now returns an empty iterator. Very strange as this was working before. The Jena model is from a dialog file that imports a number of other models, but the in-memory model has no statements (from the imports).

**Comment by agabaldon** [comment]
getUniquePropertyRange is in the ASKE dialog code, by the way. But the problem seems to be with the in-memory model.

**Comment by crapo** [comment]
Do you happen to have a small case that reproduces this error?

**Comment by crapo** [comment]
Do you happen to have a small case that reproduces this error?

**Comment by agabaldon** [comment]
Never mind. After switching branches back and forth and rebuilding, the problem went away. No idea what happened. I will now try a couple of tests and let you know so we can move forward with the PR. Thanks!

**Comment by crapo** [comment]
@agabaldon , any progress on whether this is resolved? I'm working on some new functionality that depends on what was implemented for this issue and would like to merge this branch with development before too long....

**Comment by agabaldon** [comment]
Sorry about the delay. It's working fine so we can close this.
