### ISSUE TITLE
Maven build error

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#940]
I can no longer do a build due to an error coming from Maven, "No versions available for org.osgi.service:org.osgi.service.prefs:jar:[1.1.0,1.2.0) within specified range". 

There's a discussion of this here: [https://stackoverflow.com/questions/72625637/maven-build-failed-due-to-jdt-dependencies-no-versions-available-for-org-osgi](https://stackoverflow.com/questions/72625637/maven-build-failed-due-to-jdt-dependencies-no-versions-available-for-org-osgi) 

@tuxji , what is the best solution?

**Comment by tuxji** [comment]
I like the last answer of the discussion (exclude the dependency like below), and I would try that approach if I were you to see if it works:

```
<dependency>
<groupId>org.eclipse.jdt</groupId>
<artifactId>org.eclipse.jdt.core</artifactId>
<version>3.24.0</version>
<exclusions>
    <exclusion>
        <groupId>org.osgi.service</groupId>
        <artifactId>org.osgi.service.prefs</artifactId>
    </exclusion>
</exclusions>
```

**Comment by crapo** [comment]
Maybe I don't understand this last option, but I added the exclusion but it made no difference. If I'm understanding this problem, it should go away on its own when the newer version of jars gets propagated? So maybe just wait for it to go away?

**Comment by tuxji** [comment]
@crapo I'm traveling, so I can't test changes for a while (I also saw your comment just now). I would suspect that you made the exclusion incorrectly.  However, I also see that the top answer in your StackOverflow article has been edited and seems clearer now. Its suggestion to import a bomb (bill of materials) from ECentral also makes sense.

**Comment by crapo** [comment]
I think this is resolved.
