### ISSUE TITLE
SADL enhancement validation and Integration with dependent DSLs

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#941]
@agabaldon , @AbhaMoitra , @tuxji , @kaggour , @weisenje : 
I have been working for quite a number of weeks on bringing together and completing implementation of several SADL functionalities.
1. [Implied properties](http://semanticapplicationdesignlanguage.github.io/sadl/ImpliedProperties.html), which were used in ASSERT(TM)
2. [Expanded properties](http://semanticapplicationdesignlanguage.github.io/sadl/ImpliedProperties.html), which have not been previously implemented.
3. [Unitted quantities](http://semanticapplicationdesignlanguage.github.io/sadl/UnittedQuantity.html), which have been in the SadlImplicitModel for some time and were used in ASKE.

The results of this work is in branch GH-440b. I have added many new test cases and am working to add more. I'm alerting you to this work for two reasons. 1) If it is of value to you, you may want to check it out. 2) In order to be merged into development branch, the effects on ASKE and ASSERT may need to be assessed as each of those projects implemented a portion of this functionality. They may want to leverage the SADL functionality rather than keep their own implementation, and the implementations may come into conflict. Note that it was always my intent to move these functionalities back upstream into SADL at some point.

**Comment by tuxji** [comment]
This issue was opened nearly 1 year ago.  Has branch GH-440b been merged into the development branch since then?  If so, let's say so and close this issue.

**Comment by crapo** [comment]
Yes, this has been merged into development. Issue #1043 is active and is a follow-on.
