### ISSUE TITLE
Rule error when variable is equivalent to an instance

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#951]
Given the rule "Rule R4: if x is chips then Sam likes x." (from an SWI-Prolog tutorial), it is incorrectly translated to "if x is Food then Sam likes x." One approach would be to replace all occurrences of the variable with the instance in the post-processing stage.

**Comment by crapo** [comment]
@agabaldon , For the Jena reasoner, the approach of replacing the variable with the instance and removing identities gives Jena rule "[R4: -> (http://sadl.org/test.sadl#Sam http://sadl.org/test.sadl#likes http://sadl.org/test.sadl#chips)]", which works fine.
For SWI-Prolog reasoner, what I thought was equivalent, ":- holds('http://sadl.org/test.sadl#likes', 'http://sadl.org/test.sadl#Sam', 'http://sadl.org/test.sadl#chips').", doesn't work. Suggestions for the Prolog rule?

**Comment by crapo** [comment]
@agabaldon , I guess it's simplier than I thought:
"holds('http://sadl.org/test.sadl#likes', 'http://sadl.org/test.sadl#Sam', 'http://sadl.org/test.sadl#chips')."

**Comment by agabaldon** [comment]
Not sure about the context, but yes, what you had was a rule with empty head, and you wanted a fact: holds(...). or holds(...) :- True. In SWI-Prolog, the empty head rule syntax is only used for compiler directives, import, etc.
