### ISSUE TITLE
Add tests of SWIPrologReasonerPlugin and SWIPrologTranslatorPlugin

### ISSUE THREAD

**Issue by crapo** [SemanticApplicationDesignLanguage/sadl#957]
The catch is that tests of the reasoner and translator plugins can only be successfully executed if SWI-Prolog is installed and on the path of the current development environment. The tests should not actually fail if it isn't installed.

**Comment by crapo** [comment]
@tuxji , @agabaldon : it would be nice to detect the presence (or not) of SWI-Prolog without starting it. On Linux this is easily done with the method below. Can you suggest if there is a reliable way to do so on Windows and Mac?

> `	/**
> 	 * Method to determine if SWI-Prolog is installed on the host machine
> 	 * @return true if installed else false if not
> 	 * @throws Exception unsupported operating system
> 	 */
> 	public static boolean isSWIPrologPresent() throws Exception {
> 		if (SWIPrologReasonerPlugin.isWindows()) {
> //TODO	need to activate this method for Windows			
> 			return false;
> 		}
> 		else if (SWIPrologReasonerPlugin.isMac()) {
> //TODO	need to activate this method for Windows			
> 			return false;
> 		}
> 		else if (SWIPrologReasonerPlugin.isUnix()) {
> 			String command = "which swipl"; 
> 			try {
> 				Runtime.getRuntime().exec(command);
> 			    java.util.Scanner s = new java.util.Scanner(Runtime.getRuntime().exec(command).getInputStream()).useDelimiter("\\A");
> 			    String result =  s.hasNext() ? s.next() : "";
> 				if (result.length() > 0) {
> 					return true;
> 				}
> 				System.out.println(result);
> 			} catch (IOException e) {
> 				// TODO Auto-generated catch block
> 				e.printStackTrace();
> 			} //for *NIX
> 		}
> 		else {
> 			String os = System.getProperty("os.name").toLowerCase();
> 			throw new Exception("Unsupported Operating System: " + os);
> 		}
> 		return false;
> 	}
> `

**Comment by tuxji** [comment]
Hi @crapo, your approach can work on Windows if you use "where" instead of "which" on Windows, but a faster solution is to check the existence of the program in the path using Files.exists(...), see https://stackoverflow.com/questions/934191/how-to-check-existence-of-a-program-in-the-path.  The accepted answer (the first one) was last edited in March 2021.

**Comment by agabaldon** [comment]
The same approach should work on Mac, assuming the user has added swipl to $PATH, which doesn't happen if one just installs SWI-Prolog as an app.

**Comment by crapo** [comment]
This has been done--tests added with condition.
